// Heroes, shop, and hand-made missions. All names/text original; legend characters are public domain.
'use strict';
(function (RH) {
  const E = 0, S = Math.PI / 2, W = Math.PI, N = -Math.PI / 2;

  RH.HEROES = {
    robin:   { name: 'Robin',       hp: 6, speed: 2.7, dmg: 1, weapon: 'sword', tunic: '#3f7d2c', trim: '#a9c94a', hat: '#2f5e1f', hair: '#7a4a22', skin: '#f0c9a0', icon: '🏹', blurb: 'Archer and leader. Bow shots and a quick knockout.' },
    john:    { name: 'Little John', hp: 9, speed: 2.3, dmg: 2, weapon: 'staff', tunic: '#5b6fa8', trim: '#c9b27a', hat: null,      hair: '#4a2c14', skin: '#e2b48a', icon: '💪', blurb: 'Huge and strong. Long knockouts, carries bodies fast.', big: true },
    marian:  { name: 'Marian',      hp: 5, speed: 2.8, dmg: 1, weapon: 'sword', tunic: '#9c2a3a', trim: '#e8c46a', hat: null,      hair: '#b0522a', skin: '#f3d0ae', icon: '🌹', blurb: 'Charms a guard so he sees only her.' },
    tuck:    { name: 'Friar Tuck',  hp: 7, speed: 2.1, dmg: 1, weapon: 'staff', tunic: '#7a5634', trim: '#d9c08a', hat: null,      hair: '#c8a070', skin: '#eab896', icon: '✚', blurb: 'Heals and revives friends. Throws beehives.', round: true },
    scarlet: { name: 'Will Scarlet', hp: 6, speed: 2.8, dmg: 2, weapon: 'sword', tunic: '#c0362c', trim: '#2a2a2a', hat: '#7d1d18', hair: '#2b1a10', skin: '#efc39c', icon: '💰', blurb: 'Fast blade. Tosses coin purses to lure guards.' },
    hob:     { name: 'Hob',         hp: 4, speed: 2.4, dmg: 0, weapon: null,    tunic: '#8a7a5a', trim: '#5a4a2a', hat: null,      hair: '#9a6a3a', skin: '#efc39c', icon: '🙂', blurb: 'Little John\u2019s cousin.', npc: true },
  };
  RH.HERO_ORDER = ['robin', 'john', 'marian', 'tuck', 'scarlet'];

  RH.SHOP = [
    { id: 'arrows', name: 'Bundle of arrows', desc: '+5 arrows for Robin', cost: 15, kind: 'item' },
    { id: 'potion', name: 'Healing draught', desc: 'Restores 5 health. Use from the action bar.', cost: 25, kind: 'item' },
    { id: 'yew', name: 'Yew longbow', desc: 'Robin shoots 3 tiles further', cost: 70, kind: 'up' },
    { id: 'jerkin', name: 'Leather jerkins', desc: '+2 health for the whole band', cost: 90, kind: 'up' },
    { id: 'boots', name: 'Soft boots', desc: 'Sneaking is even harder to spot', cost: 80, kind: 'up' },
    { id: 'pouch', name: 'Deep pouches', desc: '+1 beehive and +1 purse each mission', cost: 60, kind: 'up' },
  ];

  RH.MISSIONS = [
    {
      id: 'm1', title: 'The Woodcutters\u2019 Camp', place: 'Sherwood Forest', mapPos: [24, 58],
      intro: 'The Sheriff\u2019s men have seized a woodcutters\u2019 camp deep in Sherwood. They are holding Hob, Little John\u2019s cousin, inside a fenced pen, and mean to march him to Nottingham at dawn.\n\nSlip in quietly, cut Hob loose and bring everyone back to the clearing.',
      outro: 'Hob rubs his wrists and grins. \u201cI told them my cousin would come. They laughed.\u201d\n\nWord of the rescue spreads through the villages. In Nottingham, a certain lady hears of it too\u2026',
      heroes: { robin: [12, 25], john: [11, 25] },
      exit: { x: 9, y: 25, w: 7, h: 3 },
      prisoner: { id: 'hob', x: 10, y: 6 },
      objectives: ['rescue', 'exit'],
      reward: 40,
      map: [
        'TTTTTTTTTTTTTTTTTTTTTTTT',
        'TTTTTTTTbb......bbTTTTTT',
        'TTTTTp....,,,,,,....TTTT',
        'TTTT......,....,.p..TTTT',
        'TTTl..,,,,,....,,,...TTT',
        'TTT...,..xxxx....,...lTT',
        'TTb...,..x..x....,....TT',
        'TT....,..x..x....,..bbTT',
        'TT.p..,,,,,,,,,,,,....TT',
        'TT.......,....,......TTT',
        'TTTll....,....,..ll..TTT',
        'TTTT.....,....,.....TTTT',
        'TTTTTb...,,,,,,...bTTTTT',
        'TTTTT.......,.......TTTT',
        'TTTT...T....,....T..TTTT',
        'TTTbb..TT...,...TT..bTTT',
        'TTT.........,........TTT',
        'TTT...b.....,.....b..TTT',
        'TTTT........,........TTT',
        'TTTTT...T...,...T...TTTT',
        'TTTTTb......,......bTTTT',
        'TTTTTT......,......TTTTT',
        'TTTTTTT.....,.....TTTTTT',
        'TTTTTTTbb...,...bbTTTTTT',
        'TTTTTTT.....,.....TTTTTT',
        'TTTTTTTT....,....TTTTTTT',
        'TTTTTTTT.........TTTTTTT',
        'TTTTTTTTT.......TTTTTTTT',
        'TTTTTTTTTTTTTTTTTTTTTTTT',
      ],
      guards: [
        { route: [[12, 13, 2.5, S], [12, 17, 2.5, N]] },
        { route: [[14, 10, 0]], looks: [S, W + 0.5, S, E - 0.4] },
        { route: [[6, 4, 1.5], [17, 4, 1.5], [17, 8, 1.5], [6, 8, 1.5]] },
        { route: [[14, 6, 0]], looks: [W, W - 0.5, W, W + 0.5] },
      ],
      gold: [[3, 16, 10], [18, 2, 15], [2, 9, 10], [20, 7, 15]],
      tips: [
        { id: 'move', when: 'start', text: 'Tap the ground to walk there. Drag with one finger to look around. Pinch to zoom.' },
        { id: 'cone', when: 'nearGuard', text: 'The red wedge is what a guard can see. Tap \u{1F9B6} Sneak to creep: you\u2019re spotted much more slowly.' },
        { id: 'ko', when: 'nearGuard2', text: 'Creep up behind a guard, then tap him to knock him out.' },
        { id: 'tie', when: 'firstKO', text: 'He\u2019ll wake up soon! Tap the body to tie him up for good.' },
        { id: 'carry', when: 'firstTie', text: 'A guard who sees a body raises the alarm. Long-press a body with Little John to carry it into a bush.' },
        { id: 'pause', when: 'time40', text: 'Tap \u23F8 any time to pause. You can still give orders while paused.' },
        { id: 'free', when: 'nearPrisoner', text: 'Tap Hob to cut him loose.' },
        { id: 'exit', when: 'freed', text: 'Now bring everyone back to the glowing clearing. Tip: tap a portrait twice (or \u{1F465} All) to move the whole band.' },
      ],
    },
    {
      id: 'm2', title: 'Market Day', place: 'Nottingham', mapPos: [58, 50],
      intro: 'Every market day the Sheriff\u2019s collector squeezes the stallholders dry, then locks the takings in his strongroom off the square.\n\nMarian has joined the band. She knows the town, and the guards are fond of her. Steal the tax chest and bring it back out of the south gate. The townsfolk are on our side: harm none of them.',
      outro: 'The chest is heavy with coin, every penny of it wrung from honest folk. By nightfall it is back in their hands.\n\nBut the Sheriff has arrested Friar Tuck for preaching against him. He is to be made an example of.',
      heroes: { robin: [13, 29], john: [14, 29], marian: [12, 29] },
      exit: { x: 9, y: 28, w: 10, h: 3 },
      chest: { x: 13, y: 3 },
      objectives: ['steal', 'exit'],
      civilians: [[10, 11], [16, 14], [12, 18], [17, 9], [9, 15]],
      reward: 60,
      map: [
        '############################',
        '#rrrrrr.ffffffffffff.rrrrrr#',
        '#rrrrrr.f##########f.rrrrrr#',
        '#rrrrrr.f#ffffffff#f.rrrrrr#',
        '#hh.....f#ffffffff#f.....hh#',
        '#.......f#ffffffff#f.......#',
        '#rrrr...f#ffffffff#f...rrrr#',
        '#rrrr...f####ff####f...rrrr#',
        '#rrrr...ffffffffffff...rrrr#',
        '#rrrr...ffffffffffff...rrrr#',
        '#.......ffmmffffmmff.......#',
        '#cc.....ffffffffffff.....cc#',
        '#rrrr...ffmmffffmmff...rrrr#',
        '#rrrr...ffffffffffff...rrrr#',
        '#rrrr...ffffhhffffff...rrrr#',
        '#.......ffffffffffff.......#',
        '#.h.....ffmmffffmmff.....h.#',
        '#rrrrr..ffffffffffff..rrrrr#',
        '#rrrrr..fffffcffffff..rrrrr#',
        '#rrrrr..ffffffffffff..rrrrr#',
        '#rrrrr..ffffffffffff..rrrrr#',
        '#.......ffffffffffff.......#',
        '#...rrrrrr..ffff..rrrrrr...#',
        '#...rrrrrr..ffff..rrrrrr...#',
        '#h..rrrrrr..ffff..rrrrrr..h#',
        '#...........ffff...........#',
        '#####.......ffff.......#####',
        'TTTT#####...ffff...#####TTTT',
        'TTTTTTTT#...ffff...#TTTTTTTT',
        'TTTTTTTT#..........#TTTTTTTT',
        'TTTTTTTTT..........TTTTTTTTT',
        'TTTTTTTTTTTTTTTTTTTTTTTTTTTT',
      ],
      guards: [
        { route: [[13, 8, 0]], looks: [S, S - 0.7, S, S + 0.7] },
        { route: [[11, 4, 2], [16, 4, 2], [16, 6, 1], [11, 6, 1]] },
        { route: [[8, 9, 1], [19, 9, 1], [19, 20, 1], [8, 20, 1]] },
        { route: [[19, 20, 1], [8, 20, 1], [8, 9, 1], [19, 9, 1]] },
        { route: [[11, 24, 3, N], [16, 24, 3, N]] },
        { route: [[6, 5, 2], [6, 21, 2]] },
        { route: [[21, 21, 2], [21, 5, 2]] },
      ],
      gold: [[3, 11, 15], [26, 16, 15], [12, 3, 20], [24, 4, 15], [1, 24, 10]],
      tips: [
        { id: 'marian', when: 'start', text: 'Select Marian and tap \u{1F339} Charm, then tap a guard. He\u2019ll watch only her, so the others can slip past or knock him out.' },
        { id: 'chest', when: 'nearChest', text: 'Tap the chest to pick it up. Whoever carries it walks slowly.' },
      ],
    },
    {
      id: 'm3', title: 'The Castle by Night', place: 'Nottingham Castle', mapPos: [82, 30], night: true,
      intro: 'Friar Tuck sits in a cell in the castle yard, to hang at sunrise. Torches burn along the walls; the guards see less in the dark, but anyone who steps into torchlight is plain to see.\n\nIf the alarm is raised, they will move him to the dungeons, and he\u2019ll be lost. Tie up every guard you knock out, and don\u2019t let a single one see you.',
      outro: '\u201cBless you, my son!\u201d Tuck booms, then remembers to whisper. \u201cAnd bless that cook\u2019s pantry. I shall need my strength.\u201d\n\nTuck joins the band. On the road home, a red-cloaked swordsman steps from the trees with news of a treasure convoy\u2026',
      heroes: { robin: [13, 24], john: [14, 24], marian: [15, 24] },
      exit: { x: 9, y: 23, w: 10, h: 3 },
      prisoner: { id: 'tuck', x: 17, y: 2 },
      objectives: ['rescue', 'exit', 'noalarm'],
      alarmFail: true,
      reward: 80,
      torches: [[9, 5], [19, 5], [13, 9], [3, 12], [24, 12], [20, 16], [21, 18], [17, 18]],
      map: [
        '############################',
        '#rrrrrrrrrrrrrrrrrrrrrrrrrr#',
        '#rrr#ffff#ffff#ffff#ffff#rr#',
        '#rrr#ffff#ffff#ffff#ffff#rr#',
        '#rrr##ff###ff###ff###ff##rr#',
        '#ffffffffffffffffffffffffff#',
        '#ffffffffffffffffffffffffff#',
        '#ffhhfff##ffffffffff##ffhhf#',
        '#fffffff##ffffffffff##fffff#',
        '#ffffffffffffffffffffffffff#',
        '#ffccfffffffwwwwfffffffccff#',
        '#fffffffffffwwwwfffffffffff#',
        '#ffffffffffffffffffffffffff#',
        '#fffffff##ffffffffff##fffff#',
        '#ffhffff##ffffffffff##ffhff#',
        '#ffffffffffffffffffffffffff#',
        '#ffffffffffffffffffffffffff#',
        '#####ff############ff#######',
        'TT..b,,...........b,,.....TT',
        'TTwww,,wwwwwwwwwwwww,,wwwwTT',
        'TT...,,.....bb.....,,....bTT',
        'TTT..,,..T.........,,..T.TTT',
        'TTTb.,,,,,,,,,,,,,,,,....TTT',
        'TTTT..........,.......bTTTTT',
        'TTTTTb........,........TTTTT',
        'TTTTTTT.......,......TTTTTTT',
        'TTTTTTTTTTTTTTTTTTTTTTTTTTTT',
      ],
      guards: [
        { route: [[19, 18, 0]], looks: [S, S + 0.5, S, S - 0.6] },
        { route: [[21, 18, 0]], looks: [S, S - 0.5, S, S + 0.6] },
        { route: [[3, 15, 3, E], [9, 15, 3, W]] },
        { route: [[8, 12, 1], [19, 12, 1], [19, 6, 1], [8, 6, 1]] },
        { route: [[12, 5, 2, N], [21, 5, 2, N]] },
        { route: [[25, 9, 0]], looks: [W, W - 0.6, W + 0.6] },
        { route: [[24, 15, 2], [24, 6, 2]] },
      ],
      gold: [[6, 2, 20], [21, 3, 20], [2, 10, 15], [24, 20, 15]],
      tips: [
        { id: 'night', when: 'start', text: 'Night: guards see less far in the dark, but torchlight gives you away. One sighting and the mission fails.' },
        { id: 'bush', when: 'time12', text: 'Bushes and hay hide you completely, unless a guard is right next to you.' },
      ],
    },
    {
      id: 'm4', title: 'The Forest Road', place: 'The Great North Road', mapPos: [36, 32],
      intro: 'A treasure cart is rolling south to Prince John, guarded by soldiers. Will Scarlet felled an oak across the road; the carter will have to stop and clear it.\n\nStop the cart before it leaves the forest, take the chest and carry it back to camp. The carter is a hired local man. Knock him out if you must, but don\u2019t kill him.',
      outro: 'The chest is packed with silver marked for Prince John\u2019s new palace. Instead it will buy seed corn for a dozen villages.\n\nNow the Sheriff is furious. He has locked himself in his keep with the last of the taxes. It is time to pay him a visit.',
      heroes: { robin: [17, 14], john: [18, 14], marian: [19, 14], tuck: [20, 14], scarlet: [21, 14] },
      exit: { x: 16, y: 13, w: 6, h: 3 },
      convoy: { path: [[8.5, 3], [8.5, 16], [8.5, 29.5]], logStop: 1, logWait: 15, speed: 0.6 },
      objectives: ['convoy', 'exit'],
      reward: 90,
      map: [
        'TTTTTTTT,,TTTTTTTTTTTTTTTT',
        'TTTTTT..,,..TTTTTTTTTTTTTT',
        'TTTTTb..,,...TTTTTTTTTTTTT',
        'TTTT....,,....bTTTTTTTTTTT',
        'TTTT....,,.....TTTTTTTTTTT',
        'TTTb....,,......TTTTTTTTTT',
        'TTT..T..,,..b....bTTTTTTTT',
        'TTT.....,,.........TTTTTTT',
        'TTTT.b..,,..T.......TTTTTT',
        'TTTT....,,..TT.......TTTTT',
        'TTTTT...,,..........b.TTTT',
        'TTTTb...,,.............TTT',
        'TTTT....,,.....,,,,,,,..TT',
        'TTT.....,,...b.,......,.TT',
        'TTT..T..,,.....,......,.TT',
        'TTT.....,,....b,..p.p.,bTT',
        'TTTT....,,.....,,,,,,,,.TT',
        'TTTT....,,.......b.....TTT',
        'TTTTb...,,..T..........TTT',
        'TTTT....,,..TT.....b...TTT',
        'TTTT....,,.............TTT',
        'TTTTT...,,...b.....T..TTTT',
        'TTTTT...,,...........TTTTT',
        'TTTTb...,,..T......TTTTTTT',
        'TTTT....,,.........TTTTTTT',
        'TTTT..T.,,....b...TTTTTTTT',
        'TTTTT...,,.......TTTTTTTTT',
        'TTTTTb..,,......TTTTTTTTTT',
        'TTTTTT..,,....TTTTTTTTTTTT',
        'TTTTTTT.,,..TTTTTTTTTTTTTT',
        'TTTTTTTT,,TTTTTTTTTTTTTTTT',
      ],
      guards: [
        { escort: [-1.1, -1.4] },
        { escort: [1.1, -1.4] },
        { escort: [0, -2.6] },
        { route: [[11, 20, 0]], looks: [N, N - 0.7, W, N + 0.5] },
        { route: [[5, 9, 2], [5, 24, 2]] },
      ],
      gold: [[4, 7, 15], [20, 10, 20], [12, 24, 15], [5, 20, 15]],
      tips: [
        { id: 'convoy', when: 'start', text: 'The cart stops at the fallen oak for a short while. Stop it for good by knocking out the carter, then tap the cart to take the chest.' },
        { id: 'scarlet', when: 'time6', text: 'Will Scarlet: tap \u{1F4B0} Purse, then a spot. Nearby guards wander over to grab the coins.' },
        { id: 'tuck', when: 'time14', text: 'Friar Tuck: \u{1F41D} Hive stuns guards near where it lands. \u271A Heal tends wounds and revives a fallen friend.' },
      ],
    },
    {
      id: 'm5', title: 'The Sheriff\u2019s Keep', place: 'The Sheriff\u2019s Keep', mapPos: [84, 58], night: true,
      intro: 'The Sheriff of Nottingham sits in his great hall, guarding the last chest of stolen taxes and plotting revenge.\n\nCapture him alive: beat or knock him out, then tie him up so he can answer to King Richard. Take the tax chest from the treasury and get the whole band back out over the moat.',
      outro: 'The Sheriff, trussed like a Michaelmas goose, is left on the steps of the abbey with a note pinned to his cloak.\n\nThe last of the taxes go home to the people. Sherwood rings with songs that night. Long live Robin Hood!',
      heroes: { robin: [14, 25], john: [15, 25], marian: [13, 25], tuck: [16, 25], scarlet: [12, 25] },
      exit: { x: 10, y: 23, w: 8, h: 3 },
      chest: { x: 2, y: 10 },
      sheriff: { x: 14, y: 3 },
      objectives: ['sheriff', 'steal', 'exit'],
      reinforce: [[14, 18], [15, 18]],
      reward: 120,
      torches: [[13, 7], [16, 7], [10, 15], [19, 15], [11, 18], [16, 18], [6, 2], [23, 2], [8, 9]],
      map: [
        '##############################',
        '#rrrrrrrrrrrrrrrrrrrrrrrrrrrr#',
        '#rr#dddddddddddddddddddddd#rr#',
        '#rr#dddddddddddddddddddddd#rr#',
        '#rr#dd##dddddddddddddd##dd#rr#',
        '#rr#dddddddddddddddddddddd#rr#',
        '#rr##########dddd#####dd###rr#',
        '#ffffffffffffffffffffffffffff#',
        '#########ffffffffffff#########',
        '#fffffff#ffffffffffff#hhfffff#',
        '#ffffffffffffffffffffffffffff#',
        '#fffffff#ffffffffffff#fffffff#',
        '#fffffff#ffffwwwwffff#ccfffff#',
        '#########ffffwwwwffff#########',
        '#ffffffffffffffffffffffffffff#',
        '#ffhff##ffffffffffffff##ffhff#',
        '#ffffffffffffffffffffffffffff#',
        '#ccfffffffffffffffffffffffccf#',
        '#ffffffffffffffffffffffffffff#',
        '##f#########ffff##############',
        'TT..b.......,,,,.......b...TTT',
        'TT,wwwwwwwww,,,,wwwwwwwwwwwwTT',
        'TT.....b....,,,,....b......TTT',
        'TTT.........,,,,.........TTTTT',
        'TTTTb.......,,,,.......bTTTTTT',
        'TTTTTT......,,,,......TTTTTTTT',
        'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
      ],
      guards: [
        { route: [[5, 5, 2], [24, 5, 2]] },
        { route: [[12, 7, 0]], looks: [S, S - 0.6, S + 0.4] },
        { route: [[17, 7, 0]], looks: [S, S + 0.6, S - 0.4] },
        { route: [[9, 14, 1], [20, 14, 1], [20, 17, 1], [9, 17, 1]] },
        { route: [[12, 18, 0]], looks: [S, S - 0.5, S] },
        { route: [[15, 18, 0]], looks: [S, S + 0.5, S] },
        { route: [[4, 10, 0]], looks: [E, E - 0.6, E + 0.6] },
        { route: [[1, 14, 3, S], [1, 18, 3, N]] },
        { route: [[24, 7, 2], [28, 7, 2], [28, 16, 2]] },
      ],
      gold: [[27, 9, 20], [1, 12, 20], [5, 2, 25], [24, 12, 15]],
      tips: [
        { id: 'sheriff', when: 'start', text: 'The Sheriff is tough. Knock him out from behind, or beat him in a fight, then tap him to tie him up.' },
      ],
    },
  ];
})(window.RH);
