// The story campaign: twelve hand-made missions after the shape of the original's campaign.
// All mission names, maps and text are original. Legend figures are public-domain folklore.
'use strict';
(function (RH) {
  const E = 0, S = Math.PI / 2, W = Math.PI, N = -Math.PI / 2;

  RH.MISSIONS = [
    // 1 ─ find an ally in a town (solo)
    {
      id: 'm1', rank: 0, theme: 'town', title: 'A Friend in Lockwood', place: 'Lockwood village', mapPos: [20, 62], kind: 'story',
      type: 'Find an ally', captive: [2, 19], climbs: [[13, 8, 13, 6]],
      intro: 'Home from the Crusade, Robin of Locksley finds his lands seized and his name on a warrant. Only one man in Lockwood still owes him a kindness: old Wat, the steward of the manor.\n\nThe Sheriff\u2019s men hold the manor now. Get inside the yard and find Wat. Beggars hear everything; a coin may loosen a tongue.',
      outro: 'Gisela wipes the flour from her hands. \u201cThey will hang him at the Gallows Cross on market day, him and two of your old company. If you mean to stop it, go tonight.\u201d\n\nRobin pulls up his hood. Sherwood, then, and Nottingham after.',
      heroes: { robin: [9, 25] }, need: ['robin'],
      exit: { x: 6, y: 24, w: 6, h: 2 },
      objectives: ['meet:wat', 'meet:gisela', 'exit'],
      contacts: [
        { id: 'wat', name: 'Old Wat', x: 12, y: 3, look: 2, say: '\u201cMaster Robin! They told us you had died in the Holy Land.\u201d Wat drops his voice. \u201cYour friend John is taken. My girl Gisela at the mill knows the rest. Go to her.\u201d', reveals: ['gisela'] },
        { id: 'gisela', name: 'Gisela', x: 19, y: 7, look: 3, hidden: true, female: true, say: '\u201cSo you\u2019re the one Father talks about.\u201d' },
      ],
      beggars: [{ id: 'b1', x: 5, y: 22, price: 10, pays: ['s1'], say: ['Wat? He never leaves the manor yard now. But the guards drink by the gate. Look under the hay by the old well; someone hid a note there.'] }],
      scrolls: [{ id: 's1', x: 4, y: 14, hidden: true, gold: 10, text: 'A scrap of a steward\u2019s note: \u201cThe east wall by the woodshed is low. A man who can climb could be over it in a moment.\u201d Look for the rope mark.' }],
      guards: [
        { route: [[7, 8, 0]], looks: [S, S - 0.6, S, S + 0.5] },
        { route: [[8, 8, 0]], looks: [S, S + 0.6, E, S] },
        { route: [[4, 5, 2], [13, 5, 2]] },
        { route: [[8, 11, 2], [16, 11, 1], [16, 15, 2], [8, 15, 1]] },
        { route: [[17, 9, 0]], looks: [W, S, W + 0.5, N] },
        { route: [[7, 21, 2], [7, 17, 2]] },
      ],
      nobles: [[12, 14]],
      civilians: [[10, 17], [13, 12], [4, 9]],
      gold: [[2, 8, 10], [18, 2, 15], [13, 18, 10]],
      reward: 30,
      tips: [
        { id: 'move', when: 'start', text: 'Tap the ground to walk there. Drag to look around, pinch to zoom. Tap \u23F8 any time: you can still give orders while paused.' },
        { id: 'beg', when: 'nearBeggar', text: 'Tap the beggar to give him a few coins. In return he tells you where to look, and a parchment appears.' },
        { id: 'cone', when: 'nearGuard', text: 'The pale wedge is what a guard can see. Tap \u{1F9B6} Sneak to creep: you\u2019re spotted far more slowly.' },
        { id: 'purse', when: 'nearGuard2', text: 'Two greedy gate guards. Tap \u{1F4B0} Purse, then a spot near them: they\u2019ll fight over the coins. Or climb the wall at the rope mark.' },
        { id: 'noble', when: 'time50', text: 'The gentleman in fine clothes is no friend: if he sees you he runs to fetch a guard. Knock him out or keep out of his sight.' },
      ],
      map: [
        'TTTTTTTTTTTTTTTTTTTTTTTTTT',
        'TT##############TTTTwwTTTT',
        'TT#rrrrrr..h...#TT..ww.TTT',
        'TT#rrrrrr......#T...ww..TT',
        'TT#rrrrrr..,,..#..rrrww..T',
        'TT#.........,..#..rrrww..T',
        'TT#cc.......,..#..rrrww..T',
        'TT#####ff#######.....ww..T',
        'TT.....ff.......b....ww..T',
        'T..b...ff..rrrr......ww..T',
        'T......ff..rrrr...b..ww..T',
        'T.rrr..ffffffffff....ww..T',
        'T.rrr..ffffffffff....ww..T',
        'T.rrr..ff.mm..mff..b.ww..T',
        'T..h...ff......ff....ww..T',
        'T......ffffffffff....ww.TT',
        'T.rrrr.ff..h....rrr..ww.TT',
        'T.rrrr.ff.......rrr..ww.TT',
        'T......ff..b.........ww.TT',
        'TT.b...ff.....b......ww.TT',
        'TTT....ff..........TTwwTTT',
        'TTTT...ff.........TTTwwTTT',
        'TTTTT..ff........TTTTwwTTT',
        'TTTTTT.ff.......TTTTTwwTTT',
        'TTTTT.,,,,,,....TTTTTwwTTT',
        'TTTTT.,,,,,,...TTTTTTwwTTT',
        'TTTTTT.......TTTTTTTTwwTTT',
        'TTTTTTTTTTTTTTTTTTTTTTTTTT',
      ],
    },
    // 2 ─ public execution rescue in the market
    {
      id: 'm2', rank: 0, theme: 'town', title: 'The Gallows Cross', place: 'Nottingham market', mapPos: [52, 58], kind: 'story',
      type: 'Execution rescue', captive: [13, 4], climbs: [[8, 5, 10, 5]],
      intro: 'A gallows stands in Nottingham square, and Little John stands under it with his hands tied, waiting for the Sheriff to finish his breakfast.\n\nTwo officers in capes guard the cross. Officers can\u2019t be bought with coin, and a single punch only dazes them: hit them twice. Cut John loose, then get out by the south gate. One of our old company is locked in the strongroom too.',
      outro: 'John flexes his huge hands. \u201cI\u2019d have broken the rope myself in another minute.\u201d\n\nThat night in Sherwood, old friends light a fire under the great oak. An outlaw band is born. But news comes with the dawn: Will Scarlet, the swordsman, is held at Ravenscar.',
      heroes: { robin: [13, 29] }, need: ['robin'],
      exit: { x: 9, y: 28, w: 10, h: 3 },
      prisoners: [{ id: 'john', x: 13, y: 13 }],
      objectives: ['free:john', 'exit'],
      guards: [
        { type: 'officer', route: [[12, 12, 0]], looks: [S, W, S, S + 0.6] },
        { type: 'officer', route: [[15, 13, 0]], looks: [S, E, S, S - 0.6] },
        { type: 'knight', route: [[13, 8, 0]], looks: [S, S - 0.7, S, S + 0.7] },
        { route: [[11, 4, 2], [16, 4, 2], [16, 6, 1], [11, 6, 1]] },
        { route: [[8, 9, 1], [19, 9, 1], [19, 20, 1], [8, 20, 1]] },
        { route: [[11, 24, 3, N], [16, 24, 3, N]] },
        { route: [[6, 5, 2], [6, 21, 2]] },
        { route: [[21, 21, 2], [21, 5, 2]] },
      ],
      nobles: [[17, 17], [10, 15]],
      civilians: [[10, 11], [15, 16], [12, 18], [15, 10], [9, 16], [18, 13]],
      beggars: [{ id: 'b1', x: 2, y: 25, price: 10, pays: ['s1'], say: ['The cape-wearers at the cross? Sergeants, master. Hit one and he only blinks. Hit him again before he finds his voice.'] }],
      scrolls: [{ id: 's1', x: 3, y: 16, hidden: true, gold: 15, item: ['purses', 1], text: 'A cutpurse\u2019s stash, with a note: \u201cThe knight by the strongroom never moves from his post. The lane behind the west stalls is out of his sight.\u201d' }],
      gold: [[3, 11, 15], [26, 16, 15], [24, 4, 15], [1, 24, 10]],
      reward: 50,
      tips: [
        { id: 'officer', when: 'nearGuard', text: 'Caped officers ignore purses and need two blows. A knight in a great helm is tougher still. Pick them off when no one else is looking.' },
        { id: 'free', when: 'nearPrisoner', text: 'Tap John to cut him loose. Then you can select him from the portraits at the bottom.' },
        { id: 'carry', when: 'firstKO', text: 'Tap a fallen guard to search him, tie him up or carry him. A guard who finds a body raises the alarm and wakes his friend.' },
      ],
      map: [
        '############################',
        '#rrrrrr.ffffffffffff.rrrrrr#',
        '#rrrrrr.f##########f.rrrrrr#',
        '#rrrrrr.f#ffffffff#f.rrrrrr#',
        '#hh.....f#ffffffff#f.....hh#',
        '#.......f#ffffffff#f.......#',
        '#rrrr...f#ffffffff#f...rrrr#',
        '#rrrr...f####ff####f...rrrr#',
        '#rrrr...ffffffffffff...rrrr#',
        '#rrrr...ffffffffffff...rrrr#',
        '#.......ffmmffffmmff.......#',
        '#cc.....ffffffffffff.....cc#',
        '#rrrr...ffmmffffmmff...rrrr#',
        '#rrrr...ffffffffffff...rrrr#',
        '#rrrr...fffhhfffffff...rrrr#',
        '#.......ffffffffffff.......#',
        '#.h.....ffmmffffmmff.....h.#',
        '#rrrrr..ffffffffffff..rrrrr#',
        '#rrrrr..fffffcffffff..rrrrr#',
        '#rrrrr..ffffffffffff..rrrrr#',
        '#rrrrr..ffffffffffff..rrrrr#',
        '#.......ffffffffffff.......#',
        '#...rrrrrr..ffff..rrrrrr...#',
        '#...rrrrrr..ffff..rrrrrr...#',
        '#h..rrrrrr..ffff..rrrrrr..h#',
        '#...........ffff...........#',
        '#####.......ffff.......#####',
        'TTTT#####...ffff...#####TTTT',
        'TTTTTTTT#...ffff...#TTTTTTTT',
        'TTTTTTTT#..........#TTTTTTTT',
        'TTTTTTTTT..........TTTTTTTTT',
        'TTTTTTTTTTTTTTTTTTTTTTTTTTTT',
      ],
    },
    // 3 ─ night castle rescue: scale the wall
    {
      id: 'm3', rank: 0, theme: 'castle', title: 'Lanterns at Ravenscar', place: 'Ravenscar castle', mapPos: [78, 14], night: true, kind: 'story',
      type: 'Night rescue', captive: [7, 3], climbs: [[11, 18, 11, 16]],
      intro: 'Will Scarlet, the quickest blade in the shire, waits in a cell at Ravenscar for the hangman\u2019s cart.\n\nThe walls are lit with lanterns. Guards see less far in the dark, but anyone in lantern light is plain to see. Robin can scale the wall at the rope mark and let a rope down for John. Archers on the walls shoot from afar.',
      outro: 'Will Scarlet rubs his wrists, then grins and draws a sling from his boot. \u201cThey took my sword. They didn\u2019t think to take this.\u201d\n\nA sling, a short temper and a quick blade: the band is three. In Nottingham, a message waits for Robin at the chapel of St Anne.',
      heroes: { robin: [13, 24], john: [14, 24] }, need: ['robin'],
      exit: { x: 9, y: 23, w: 10, h: 3 },
      prisoners: [{ id: 'scarlet', x: 17, y: 2 }],
      objectives: ['free:scarlet', 'exit'],
      torches: [[9, 5], [19, 5], [13, 9], [3, 12], [24, 12], [20, 16], [21, 18], [17, 18]],
      guards: [
        { route: [[19, 18, 0]], looks: [S, S + 0.5, S, S - 0.6] },
        { route: [[21, 18, 0]], looks: [S, S - 0.5, S, S + 0.6] },
        { type: 'archer', route: [[3, 15, 3, E], [9, 15, 3, W]] },
        { route: [[8, 12, 1], [19, 12, 1], [19, 6, 1], [8, 6, 1]] },
        { route: [[12, 5, 2, N], [21, 5, 2, N]] },
        { type: 'archer', route: [[25, 9, 0]], looks: [W, W - 0.6, W + 0.6] },
        { route: [[24, 15, 2], [24, 6, 2]] },
        { type: 'officer', route: [[16, 3, 0]], looks: [S, W, S, E] },
      ],
      gold: [[6, 2, 20], [21, 3, 20], [2, 10, 15], [24, 20, 15]],
      reward: 60,
      tips: [
        { id: 'night', when: 'start', text: 'Night: guards see less far in the dark, but torchlight gives you away. Bushes and hay hide you unless a guard is right beside you.' },
        { id: 'climb', when: 'time6', text: 'Tap the rope mark on the wall with Robin to climb it. Once he\u2019s over, the others can climb too.' },
        { id: 'archer', when: 'nearGuard', text: 'Archers shoot from a distance once they\u2019ve seen you. Close in fast, or keep out of their sight.' },
      ],
      map: [
        '############################',
        '#rrrrrrrrrrrrrrrrrrrrrrrrrr#',
        '#rrr#ffff#ffff#ffff#ffff#rr#',
        '#rrr#ffff#ffff#ffff#ffff#rr#',
        '#rrr##ff###ff###ff###ff##rr#',
        '#ffffffffffffffffffffffffff#',
        '#ffffffffffffffffffffffffff#',
        '#ffhhfff##ffffffffff##ffhhf#',
        '#fffffff##ffffffffff##fffff#',
        '#ffffffffffffffffffffffffff#',
        '#ffccfffffffwwwwfffffffccff#',
        '#fffffffffffwwwwfffffffffff#',
        '#ffffffffffffffffffffffffff#',
        '#fffffff##ffffffffff##fffff#',
        '#ffhffff##ffffffffff##ffhff#',
        '#ffffffffffffffffffffffffff#',
        '#ffffffffffffffffffffffffff#',
        '#####ff############ff#######',
        'TT..b,,...........b,,.....TT',
        'TTwww,,wwwwwwwwwwwww,,wwwwTT',
        'TT...,,.....bb.....,,....bTT',
        'TTT..,,..T.........,,..T.TTT',
        'TTTb.,,,,,,,,,,,,,,,,....TTT',
        'TTTT..........,.......bTTTTT',
        'TTTTTb........,........TTTTT',
        'TTTTTTT.......,......TTTTTTT',
        'TTTTTTTTTTTTTTTTTTTTTTTTTTTT',
      ],
    },
    // 4 ─ social infiltration via a chain of beggars
    {
      id: 'm4', rank: 1, theme: 'town', title: 'Vespers', place: 'Nottingham back streets', mapPos: [64, 68], night: true, kind: 'story',
      type: 'Beggars\u2019 trail', captive: [22, 14],
      intro: 'A note in a lady\u2019s hand: \u201cAt vespers, St Anne\u2019s. Come alone, or come quietly.\u201d No name, only a pressed rose.\n\nThe chapel is somewhere in the back streets, and the Sheriff\u2019s men are thick on the ground. Follow the beggars: each knows a little, and each will point you to the next. Gentlemen out late will run for the watch if they see you.',
      outro: 'Lady Marian of Leaford lowers her hood. \u201cThe Sheriff dines at my father\u2019s table and talks too much. I can be your eyes in his house.\u201d\n\nShe has heard that Prince John meets his barons at Blackmere keep in three days. Whatever he plans, the outlaws mean to hear it.',
      heroes: { robin: [10, 25], john: [11, 25], scarlet: [12, 25] }, need: ['robin'],
      exit: { x: 7, y: 24, w: 8, h: 3 },
      objectives: ['meet:marian', 'exit'],
      contacts: [{ id: 'marian', name: 'the hooded lady', x: 10, y: 5, hidden: true, joins: 'marian', female: true, say: '\u201cYou took your time, Robin of Locksley.\u201d' }],
      beggars: [
        { id: 'b1', x: 6, y: 21, price: 10, pays: ['b2'], say: ['St Anne\u2019s? Old Mother Brede by the tannery yard knows the way. Look east, past the fountain.'] },
        { id: 'b2', x: 22, y: 9, hidden: true, price: 15, pays: ['s1', 'b3'], say: ['A lady in a grey hood, yes. She left something in the cooper\u2019s yard. Then ask Lame Tom by the west wall.'] },
        { id: 'b3', x: 3, y: 10, hidden: true, price: 10, pays: ['marian'], say: ['The chapel lies north, behind the high wall. She is inside, at the altar. Mind the watchman at the door.'] },
      ],
      scrolls: [{ id: 's1', x: 12, y: 15, hidden: true, gold: 10, item: ['apples', 3], text: 'A basket of apples and a note: \u201cA guard who hears a thump behind him always turns to look.\u201d Throw an apple (Will Scarlet) to turn a guard\u2019s head.' }],
      torches: [[11, 8], [7, 11], [17, 11], [11, 21], [2, 15], [23, 15], [14, 3]],
      guards: [
        { type: 'halberd', route: [[11, 8, 0]], looks: [S, S - 0.6, S + 0.6] },
        { type: 'officer', route: [[7, 11, 2], [22, 11, 2]] },
        { route: [[2, 12, 2], [2, 17, 2]] },
        { route: [[23, 20, 2], [23, 12, 2]] },
        { route: [[7, 2, 1], [14, 2, 1], [14, 8, 1], [7, 8, 1]] },
        { route: [[8, 20, 2], [17, 20, 2]] },
      ],
      nobles: [[12, 13], [16, 21]],
      gold: [[2, 22, 10], [23, 5, 15], [23, 18, 10]],
      treasure: { id: 'cup', name: 'the Abbot\u2019s silver cup', x: 22, y: 2 },
      reward: 60,
      tips: [
        { id: 'chain', when: 'start', text: 'Follow the trail of beggars. Pay each one and a new beggar, parchment or person appears. Look for the gold rings on the map.' },
        { id: 'apple', when: 'time30', text: 'Will Scarlet: \u{1F34E} Apple turns one guard\u2019s head toward where it lands. \u{1FAA8} Sling knocks a guard out from six tiles away.' },
      ],
      map: [
        'TTTTTTTTTTTTTTTTTTTTTTTTTT',
        'T########################T',
        'T#rrrr.ffffffff.rrrrr...#T',
        'T#rrrr.f######f.rrrrr...#T',
        'T#rrrr.f#dddd#f.rrrrr...#T',
        'T#.....f#dddd#f.........#T',
        'T#.h...f#dddd#f....h....#T',
        'T#rrr..f##dd##f..rrrrr..#T',
        'T#rrr..ffffffff..rrrrr..#T',
        'T#rrr..f......f..rrrrr..#T',
        'T#.....f.rrrr.f.........#T',
        'T#ffffff.rrrr.ffffffffff#T',
        'T#f......rrrr..........f#T',
        'T#f.rrr..........rrrr..f#T',
        'T#f.rrr..cc..h...rrrr..f#T',
        'T#f.rrr..........rrrr..f#T',
        'T#f.......rrrrr........f#T',
        'T#ffffff..rrrrr..ffffff.#T',
        'T#rrrr.f..rrrrr..f.rrrr.#T',
        'T#rrrr.f.........f.rrrr.#T',
        'T#rrrr.ffffffffff..rrrr.#T',
        'T#.........f..........h.#T',
        'T#.c.rrrr..f..rrrrr.....#T',
        'T#...rrrr..f..rrrrr..c..#T',
        'T#####.....f......#######T',
        'TTTTT......,......TTTTTTTT',
        'TTTTTT....,,,....TTTTTTTTT',
        'TTTTTTTTTTTTTTTTTTTTTTTTTT',
      ],
    },
    // 5 ─ fog castle: eavesdrop on the council
    {
      id: 'm5', rank: 1, theme: 'castle', title: 'The Prince\u2019s Council', place: 'Blackmere keep', mapPos: [92, 38], weather: 'fog', kind: 'story',
      type: 'Eavesdrop', captive: [26, 10], climbs: [[6, 20, 6, 18]],
      intro: 'Prince John has called his barons to Blackmere keep. Fog lies thick on the moat: a gift from God, says Tuck\u2019s cousin, who sold us the plan of the hall.\n\nReach the listening gallery at the east end of the great hall and stand there unseen until you have heard enough. Knights in great helms guard the Prince: arrows glance off them. Halberdiers won\u2019t stoop for coins.',
      outro: '\u201c\u2026and while my brother rots in an Austrian prison, his ransom will rot in my treasury.\u201d\n\nKing Richard is alive and held for ransom, and the Prince means to keep him there. The outlaws will raise the ransom themselves, one stolen purse at a time. Pay into the King\u2019s Ransom chest at camp.',
      heroes: { robin: [14, 25], john: [15, 25], marian: [13, 25], scarlet: [12, 25] }, need: ['robin'],
      exit: { x: 10, y: 23, w: 8, h: 3 },
      objectives: ['listen:gallery', 'exit'],
      props: [{ id: 'gallery', kind: 'listen', x: 24, y: 5, dur: 5, say: 'The Prince\u2019s voice carries: \u201cLet Richard\u2019s ransom gather dust. By Michaelmas the crown is mine.\u201d You have heard enough.' }],
      nobles: [[14, 3], [10, 4], [18, 3]],
      guards: [
        { type: 'knight', route: [[12, 2, 0]], looks: [S, E, S] },
        { type: 'knight', route: [[20, 5, 2], [5, 5, 2]] },
        { type: 'halberd', route: [[13, 7, 0]], looks: [S, S - 0.6, S + 0.4] },
        { type: 'halberd', route: [[16, 7, 0]], looks: [S, S + 0.6, S - 0.4] },
        { route: [[9, 14, 1], [20, 14, 1], [20, 17, 1], [9, 17, 1]] },
        { route: [[12, 18, 0]], looks: [S, S - 0.5, S] },
        { type: 'archer', route: [[4, 10, 0]], looks: [E, E - 0.6, E + 0.6] },
        { route: [[1, 14, 3, S], [1, 18, 3, N]] },
        { type: 'officer', route: [[24, 7, 2], [28, 7, 2], [28, 16, 2]] },
      ],
      gold: [[27, 9, 20], [1, 12, 20], [5, 2, 25], [24, 12, 15]],
      treasure: { id: 'seal', name: 'the Great Seal of the barons', x: 25, y: 2 },
      reward: 80,
      tips: [
        { id: 'fog', when: 'start', text: 'Fog: everyone sees a shorter way. Use it to cross the open bailey.' },
        { id: 'listen', when: 'nearProp', text: 'Stand on the listening spot and stay still. If anyone sees you, you lose what you\u2019ve heard so far.' },
      ],
      map: [
        '##############################',
        '#rrrrrrrrrrrrrrrrrrrrrrrrrrrr#',
        '#rr#dddddddddddddddddddddd#rr#',
        '#rr#dddddddddddddddddddddd#rr#',
        '#rr#dd##dddddddddddddd##dd#rr#',
        '#rr#dddddddddddddddddddddd#rr#',
        '#rr##########dddd#####dd###rr#',
        '#ffffffffffffffffffffffffffff#',
        '#########ffffffffffff#########',
        '#fffffff#ffffffffffff#hhfffff#',
        '#ffffffffffffffffffffffffffff#',
        '#fffffff#ffffffffffff#fffffff#',
        '#fffffff#ffffwwwwffff#ccfffff#',
        '#########ffffwwwwffff#########',
        '#ffffffffffffffffffffffffffff#',
        '#ffhff##ffffffffffffff##ffhff#',
        '#ffffffffffffffffffffffffffff#',
        '#ccfffffffffffffffffffffffccf#',
        '#ffffffffffffffffffffffffffff#',
        '##f#########ffff##############',
        'TT..b.......,,,,.......b...TTT',
        'TT,wwwwwwwww,,,,wwwwwwwwwwwwTT',
        'TT.....b....,,,,....b......TTT',
        'TTT.........,,,,.........TTTTT',
        'TTTTb.......,,,,.......bTTTTTT',
        'TTTTTT......,,,,......TTTTTTTT',
        'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
      ],
    },
    // 6 ─ the friar in a hanging cage
    {
      id: 'm6', rank: 1, theme: 'castle', title: 'The Hanging Cage', place: 'Ravenscar inner yard', mapPos: [62, 24], night: true, kind: 'story',
      type: 'Cage rescue', captive: [2, 4],
      intro: 'Friar Tuck preached against the Prince on Ravenscar\u2019s market cross. Now he hangs in an iron cage over the inner yard, singing hymns loudly enough to annoy the whole garrison.\n\nThe moat is too wide to swim. Shoot through the rope that holds the drawbridge plank. Inside, work the winch to lower the cage, then cut Tuck out.',
      outro: '\u201cMy knees,\u201d groans Tuck, \u201cwere not made for cages.\u201d Then, brightening: \u201cBut I know a brewer in Sherwood who owes me a favour, and my bees will be missing me.\u201d\n\nTuck brings his ale and his beehives to camp. Set men to the brewery and the skeps.',
      heroes: { robin: [12, 22], john: [13, 22], marian: [11, 22], scarlet: [14, 22] }, need: ['robin'],
      exit: { x: 9, y: 21, w: 8, h: 3 },
      prisoners: [{ id: 'tuck', x: 13, y: 11, cage: 'winch' }],
      objectives: ['free:tuck', 'exit'],
      props: [
        { id: 'plankT', kind: 'target', x: 9, y: 16, plank: [[12, 17], [12, 18]], label: '\u{1F3AF} Shoot the plank rope' },
        { id: 'winch', kind: 'winch', x: 20, y: 5 },
      ],
      torches: [[5, 14], [20, 14], [13, 10], [4, 4], [21, 4], [12, 3]],
      guards: [
        { route: [[12, 12, 0]], looks: [S, W, S] },
        { route: [[14, 12, 0]], looks: [S, E, S] },
        { route: [[4, 14, 0]], looks: [S, S - 0.6, E] },
        { route: [[21, 14, 0]], looks: [S, S + 0.6, W] },
        { type: 'archer', route: [[3, 10, 2], [8, 10, 2]] },
        { type: 'officer', route: [[18, 4, 1], [23, 4, 1], [23, 11, 1], [18, 11, 1]] },
        { route: [[2, 3, 2], [8, 3, 2]] },
        { type: 'halberd', route: [[21, 5, 0]], looks: [W, S, N] },
      ],
      gold: [[1, 13, 15], [24, 13, 15], [12, 2, 20]],
      reward: 70,
      tips: [
        { id: 'plank', when: 'start', text: 'The plank bridge is tied up on the far bank. Select Robin or Marian, tap \u{1F3F9} Bow, then tap the target post to cut the rope.' },
        { id: 'winch', when: 'nearProp', text: 'The winch creaks: guards nearby will come to look. Clear them away first.' },
      ],
      map: [
        '##########################',
        '#rrrrrrrr#ffffff#rrrrrrrr#',
        '#rrrrrrrr#ffffff#rrrrrrrr#',
        '#ffffffff#ffffff#ffffffff#',
        '#ffhhffffffffffffffffccff#',
        '#ffffffffffffffffffffffff#',
        '#fffccffff######fffffffff#',
        '#ffffffff#rrrrrr#ffffhhff#',
        '#ffffffff#rrrrrr#ffffffff#',
        '#ffffffff#rrrrrr#ffffffff#',
        '#ffffffffffffffffffffffff#',
        '#ffccfffffffffffffffccfff#',
        '#ffffffffffffffffffffffff#',
        '#ffffhfffffffffffffffffff#',
        '#ffffffffffffffffffhhffff#',
        '####ff##############ff####',
        'T.b.,,.....b.........,,.TT',
        'wwwwwwwwwwwwwwwwwwwwwwwwww',
        'wwwwwwwwwwwwwwwwwwwwwwwwww',
        'T.b..........b......b...TT',
        'T.........,,,,.........TTT',
        'TT.......,,,,,,.......TTTT',
        'TTb......,,,,,,......bTTTT',
        'TTT.......,,,,.......TTTTT',
        'TTTTT......,,......TTTTTTT',
        'TTTTTTTTTTTTTTTTTTTTTTTTTT',
      ],
    },
    // 7 ─ the archery contest is a trap
    {
      id: 'm7', rank: 2, theme: 'town', title: 'The Sheriff\u2019s Tourney', place: 'Nottingham lists', mapPos: [40, 46], kind: 'story',
      type: 'Archery contest', captive: [24, 18],
      intro: 'The Sheriff offers an arrow of silver to the finest archer in England. Every fool in the shire knows it is bait for Robin Hood, and Robin is going anyway, in a borrowed hood.\n\nHit three targets. The aim sways: loose your arrow when the ring is steady. John and Tuck are hidden in the town in case it goes wrong.',
      outro: 'They found the silver arrow afterwards, still quivering in the Sheriff\u2019s own chair. Nobody quite remembers how it got there.\n\nBut there is worse news. Sir Hugo de Vane, the Prince\u2019s man, has claimed Marian\u2019s hand. The wedding is at Blackmere church, and it is tomorrow.',
      heroes: { robin: [13, 10] }, need: ['robin'], slots: 0,
      exit: { x: 8, y: 24, w: 12, h: 3 },
      contest: { need: 3 },
      prisoners: [{ id: 'john', x: 4, y: 4, friend: true, name: 'Little John' }, { id: 'tuck', x: 25, y: 11, friend: true, name: 'Friar Tuck' }],
      objectives: ['contest', 'free:john', 'free:tuck', 'exit'],
      props: [
        { id: 't1', kind: 'target', contest: true, x: 10, y: 4 },
        { id: 't2', kind: 'target', contest: true, x: 13, y: 4 },
        { id: 't3', kind: 'target', contest: true, x: 16, y: 4 },
      ],
      guards: [
        { route: [[6, 5, 0]], looks: [E, E - 0.4], watch: true },
        { route: [[21, 5, 0]], looks: [W, W + 0.4], watch: true },
        { route: [[6, 9, 0]], looks: [E], watch: true },
        { route: [[21, 9, 0]], looks: [W], watch: true },
        { type: 'officer', route: [[13, 13, 0]], looks: [N, N + 0.4], watch: true },
        { type: 'archer', route: [[4, 13, 0]], looks: [E], watch: true },
        { route: [[8, 19, 2], [19, 19, 2]] },
        { route: [[13, 22, 0]], looks: [S, N] },
        { type: 'knight', route: [[24, 13, 0]], looks: [W, S] },
      ],
      civilians: [[5, 3], [22, 3], [5, 11], [22, 11], [10, 13], [17, 13], [4, 17], [23, 17]],
      nobles: [[18, 13]],
      gold: [[1, 22, 15], [26, 22, 15], [2, 18, 10]],
      treasure: { id: 'arrow', name: 'the Silver Arrow', x: 14, y: 3 },
      reward: 80,
      tips: [
        { id: 'aim', when: 'start', text: 'Tap \u{1F3F9} Bow, then a target. Watch the swaying ring over it: Robin looses half a second after you tap, so tap when it is about to settle.' },
        { id: 'sprung', when: 'sprung', text: 'Run! Find John (in the hay by the north-west stands) and Tuck (by the east stalls). Tap each to call him over, then everyone out the south gate.' },
      ],
      map: [
        '############################',
        '#rrrr..................rrrr#',
        '#rrrr..xxxxxxxxxxxxxx..rrrr#',
        '#......x............x......#',
        '#.hh...x............x...hh.#',
        '#......x............x......#',
        '#rrr...x............x...rrr#',
        '#rrr...x............x...rrr#',
        '#rrr...x............x...rrr#',
        '#......x............x......#',
        '#.mm...x............x...mm.#',
        '#......x............x......#',
        '#rrr...xxxxxx..xxxxxx...rrr#',
        '#rrr......................r#',
        '#.rrrr..ffffffffffff..rrrr.#',
        '#.rrrr..f..........f..rrrr.#',
        '#.rrrr..f..rrrrrr..f..rrrr.#',
        '#.......f..rrrrrr..f.......#',
        '#.h.....f..rrrrrr..f.....c.#',
        '#.......ffffffffffff.......#',
        '#rrrrr.......ff.......rrrrr#',
        '#rrrrr.......ff.......rrrrr#',
        '#.....b......ff......b.....#',
        '#######......ff......#######',
        'TTTTTT#......ff......#TTTTTT',
        'TTTTTT#..............#TTTTTT',
        'TTTTTTTT............TTTTTTTT',
        'TTTTTTTTTTTTTTTTTTTTTTTTTTTT',
      ],
    },
    // 8 ─ crash a forced wedding
    {
      id: 'm8', rank: 2, theme: 'town', title: 'Bells for a Bride', place: 'Blackmere church', mapPos: [90, 62], kind: 'story',
      type: 'Wedding rescue', captive: [26, 19],
      intro: 'The bells of Blackmere ring for a wedding nobody wants. Marian stands at the altar beside Sir Hugo de Vane, and half the Prince\u2019s guard stands in the square.\n\nRaise the King\u2019s banner over the east gate: every loyal Prince\u2019s man in the square will run to tear it down. Then storm the church, free Marian and beat Sir Hugo. He is a master swordsman and won\u2019t leave the church: retreat and heal if you must.',
      outro: 'Sir Hugo de Vane is found that evening, still tied to the bell rope, ringing every time he struggles.\n\nMarian is safe. But in the rush, Robin was taken at the church door and dragged to Nottingham gaol. Without him, the band must find its own way.',
      heroes: { robin: [12, 28], john: [13, 28], tuck: [14, 28], scarlet: [15, 28] }, need: ['robin'],
      exit: { x: 9, y: 27, w: 10, h: 3 },
      prisoners: [{ id: 'marian', x: 2, y: 2 }],
      objectives: ['use:banner', 'free:marian', 'boss', 'exit'],
      props: [{ id: 'banner', kind: 'banner', x: 26, y: 8, to: [22, 9], lure: ['sq'], say: 'The King\u2019s lions fly over the east gate! The Prince\u2019s men run to tear them down.' }],
      guards: [
        { boss: true, name: 'Sir Hugo de Vane', type: 'boss', route: [[5, 3, 0]], looks: [S, E, S], hp: 12 },
        { tag: 'sq', route: [[5, 7, 0]], looks: [S, S - 0.5] },
        { tag: 'sq', route: [[6, 7, 0]], looks: [S, S + 0.5] },
        { tag: 'sq', type: 'officer', route: [[9, 11, 2], [24, 11, 2]] },
        { tag: 'sq', route: [[10, 8, 1], [24, 8, 1], [24, 15, 1], [10, 15, 1]] },
        { tag: 'sq', route: [[24, 15, 1], [10, 15, 1], [10, 8, 1], [24, 8, 1]] },
        { tag: 'sq', type: 'halberd', route: [[16, 13, 0]], looks: [S, W, E] },
        { type: 'knight', route: [[8, 3, 0]], looks: [W, S] },
        { route: [[8, 21, 2], [19, 21, 2]] },
        { type: 'archer', route: [[13, 25, 0]], looks: [W, N, E, N] },
      ],
      nobles: [[8, 5], [3, 5], [17, 19], [20, 13]],
      civilians: [[12, 9], [18, 12], [21, 20], [6, 20]],
      gold: [[5, 16, 15], [26, 20, 15], [2, 9, 15]],
      reward: 90,
      tips: [
        { id: 'banner', when: 'start', text: 'The banner is on the east gate (marked on the map). Get one man there unseen and tap it.' },
        { id: 'boss', when: 'used:banner', text: 'Sir Hugo holds the church. Fight him with swipes: thrust (swipe up) can\u2019t be blocked, parry (back-and-forth) leaves him open.' },
      ],
      map: [
        '############################',
        '#dddddddddd#rrrrrrrrrrrrrrr#',
        '#dddddddddd#rrrrrrrrrrrrrrr#',
        '#dddddddddd#...............#',
        '#dddddddddd#..rrrr...rrrr..#',
        '#dddddddddd#..rrrr...rrrr..#',
        '#####dd#####..rrrr...rrrr..#',
        '#....ff....................#',
        '#.b..ff..ffffffffffffffff..#',
        '#....ff..f..............f..#',
        '#rrr.ff..f..mm....mm....f..#',
        '#rrr.ffffffffffffffffffff..#',
        '#rrr.ff..f..............f..#',
        '#....ff..f..mm....mm....f..#',
        '#.h..ff..f..............f..#',
        '#....ff..ffffffffffffffff..#',
        '#rrrr..........hh......rrrr#',
        '#rrrr.....rrrrrr.......rrrr#',
        '#rrrr.....rrrrrr.......rrrr#',
        '#.........rrrrrr...........#',
        '#..c.....................c.#',
        '#rrrrr..ffffffffffff..rrrrr#',
        '#rrrrr..f..........f..rrrrr#',
        '#rrrrr..f..b....b..f..rrrrr#',
        '#.......f..........f.......#',
        '######..f..........f..######',
        'TTTTT#..ffffffffffff..#TTTTT',
        'TTTTT##.....ffff.....##TTTTT',
        'TTTTTTT#....ffff....#TTTTTTT',
        'TTTTTTTT............TTTTTTTT',
      ],
    },
    // 9 ─ the leader is captured: play without him
    {
      id: 'm9', rank: 2, theme: 'town', title: 'The Captain Taken', place: 'Nottingham gaol', mapPos: [54, 38], weather: 'fog', kind: 'story',
      type: 'Escape', captive: [8, 2], climbs: [[5, 10, 5, 8]],
      intro: 'Robin is in Nottingham gaol, and the Sheriff has sent to London for a hangman worthy of him.\n\nWithout Robin, Marian or Will can climb at the rope mark. The sergeant of the watch checks on his gate guard every round: if the man is missing, he rings the alarm. Charm him, slip past him, or leave him standing.',
      outro: '\u201cYou took your time,\u201d says Robin, which Marian points out is her line.\n\nIn the gaol office they find a sealed letter, taken from a royal messenger. It bears King Richard\u2019s own seal, and it must reach the Queen Mother\u2019s boatman at Blackmere docks before dawn.',
      heroes: { john: [12, 26], marian: [11, 26], tuck: [13, 26], scarlet: [14, 26] }, need: [],
      exit: { x: 9, y: 25, w: 8, h: 2 },
      prisoners: [{ id: 'robin', x: 5, y: 2 }],
      objectives: ['free:robin', 'exit'],
      guards: [
        { tag: 'gate', route: [[12, 10, 0]], looks: [S, S - 0.6, S + 0.6] },
        { type: 'officer', name: 'the sergeant', check: [12, 11, 'gate'], route: [[7, 12, 1], [12, 11, 2], [18, 12, 1], [12, 11, 2]] },
        { route: [[3, 5, 2], [22, 5, 2]] },
        { type: 'archer', route: [[20, 7, 0]], looks: [W, W - 0.6, S] },
        { route: [[6, 6, 0]], looks: [N, W, E] },
        { type: 'halberd', route: [[22, 2, 0]], looks: [S, W] },
        { route: [[1, 14, 2], [1, 22, 2], [24, 22, 2], [24, 14, 2]] },
        { route: [[15, 15, 2], [8, 15, 2]] },
      ],
      nobles: [[17, 19]],
      civilians: [[7, 20], [18, 16]],
      gold: [[23, 4, 20], [1, 13, 10], [22, 24, 15]],
      treasure: { id: 'keys', name: 'the Sheriff\u2019s golden keys', x: 21, y: 3 },
      reward: 90,
      tips: [
        { id: 'noRobin', when: 'start', text: 'No Robin today. Marian\u2019s \u{1F339} Charm keeps a guard at his post but blind to you; Tuck\u2019s \u{1F37A} Ale puts any guard to sleep where he stands.' },
        { id: 'check', when: 'nearGuard', text: 'The caped sergeant walks his round and checks on the gate guard. If that guard is gone from his post, the alarm goes up.' },
      ],
      map: [
        'TTTTTTTTTTTTTTTTTTTTTTTTTT',
        'T########################T',
        'T#dd#dd#dd#rrrrrrrr#ffff#T',
        'T#dd#dd#dd#rrrrrrrr#ffff#T',
        'T##f##f##f#rrrrrrrr#fccf#T',
        'T#ffffffffffffffffffffff#T',
        'T#ffffffffffffffffffffff#T',
        'T#fhhffffffffffffffffhff#T',
        'T#ffffffffffffffffffffff#T',
        'T###########ff###########T',
        'T..........,ff,..........T',
        'T.rrrr.....,,,,.....rrrr.T',
        'T.rrrr..............rrrr.T',
        'T.rrrr..b........b..rrrr.T',
        'T........................T',
        'T..rrrr..ffffffff..rrrr..T',
        'T..rrrr..f......f..rrrr..T',
        'T..rrrr..f..hh..f..rrrr..T',
        'T........f......f........T',
        'T.rrr....ffffffff....rrr.T',
        'T.rrr................rrr.T',
        'T.rrr..c..........c..rrr.T',
        'T........................T',
        'TT.b....rrr....rrr....b.TT',
        'TTT.....rrr....rrr.....TTT',
        'TTTT......,,,,,,......TTTT',
        'TTTTT.....,,,,,,.....TTTTT',
        'TTTTTTTTTTTTTTTTTTTTTTTTTT',
      ],
    },
    // 10 ─ carry a letter, no killing
    {
      id: 'm10', rank: 3, theme: 'town', title: 'The Midnight Letter', place: 'Blackmere docks', mapPos: [77, 72], night: true, kind: 'story',
      type: 'Courier', captive: [2, 5],
      intro: 'King Richard\u2019s letter must reach the boatman at the end of the north pier tonight. Whoever carries it walks at full speed, but hold on to it: if he falls, it falls with him.\n\nThe Queen Mother has asked one thing. Not a drop of blood tonight: a single death and the boatman will not sail. Use nets, ale, the sling and bare fists.',
      outro: 'The boatman tucks the letter inside his coat and pushes off into the mist without a word.\n\nIn a week, the barons will know the King lives. Some will stay loyal to the Prince. Some will march with us. Robin calls them to Blackmere.',
      heroes: { robin: [4, 25], john: [5, 25], marian: [3, 25], tuck: [6, 25], scarlet: [4, 26] }, need: ['robin'],
      exit: { x: 2, y: 24, w: 6, h: 3 },
      chest: { x: 6, y: 24, letter: true },
      contacts: [{ id: 'boatman', name: 'the boatman', x: 26, y: 7, needs: 'letter', wait: '\u201cNo letter, no boat.\u201d', say: '\u201cFor the King.\u201d He tucks it away and casts off.' }],
      objectives: ['deliver', 'nokill', 'exit'],
      torches: [[20, 6], [20, 12], [20, 19], [10, 6], [10, 12], [2, 19], [24, 7]],
      guards: [
        { route: [[21, 7, 0]], looks: [W, S, N] },
        { route: [[20, 2, 2], [20, 17, 2]] },
        { type: 'officer', route: [[3, 6, 1], [19, 6, 1]] },
        { route: [[19, 12, 1], [3, 12, 1]] },
        { type: 'archer', route: [[19, 4, 0]], looks: [S, W] },
        { route: [[3, 19, 2], [19, 19, 2]] },
        { type: 'halberd', route: [[22, 19, 0]], looks: [W, N] },
        { route: [[2, 8, 1], [2, 17, 1]] },
        { type: 'knight', route: [[12, 17, 0]], looks: [N, E, W] },
      ],
      gold: [[17, 5, 20], [9, 18, 15], [23, 19, 20]],
      reward: 100,
      tips: [
        { id: 'letter', when: 'start', text: 'Pick up the letter by the cart. The carrier keeps full speed. Deliver it by walking up to the boatman and tapping him.' },
        { id: 'nokill', when: 'time6', text: 'No killing tonight. Swords strike with the flat of the blade, but an arrow kills: use Scarlet\u2019s sling, John\u2019s nets, Tuck\u2019s ale and knockouts instead.' },
      ],
      map: [
        'TTTTTTTTTTTTTTTTTTTTwwwwwwww',
        'Trrrrr..rrrrrr..rrr.fwwwwwww',
        'Trrrrr..rrrrrr..rrr.fwwwwwww',
        'Trrrrr..rrrrrr..rrr.fwwwwwww',
        'T...................fwwwwwww',
        'T..cc......h......c.fwwwwwww',
        'T.ffffffffffffffffffffwwwwww',
        'T.f.................fddddddw',
        'T.f.rrrr..rrrr..rr..fwwwwwww',
        'T.f.rrrr..rrrr..rr..fwwwwwww',
        'T.f.rrrr..rrrr......fwwwwwww',
        'T.f.................fwwwwwww',
        'T.ffffffffffffffffffffwwwwww',
        'T.....c...h.....cc..fwwwwwww',
        'Trrrr..rrrrr..rrrr..fwwwwwww',
        'Trrrr..rrrrr..rrrr..fwwwwwww',
        'Trrrr..rrrrr..rrrr..fwwwwwww',
        'T...................fwwwwwww',
        'T..h...cc......c....fwwwwwww',
        'T.ffffffffffffffffffddddwwww',
        'T.f.................fwwwwwww',
        'T.f.rrrrr..rrrr..rr.fwwwwwww',
        'T.f.rrrrr..rrrr..rr.fwwwwwww',
        'T.f.................fwwwwwww',
        'Tb..................fwwwwwww',
        'T..,,,,.....b.......fwwwwwww',
        'TT.,,,,............TTwwwwwww',
        'TTTTTTTTTTTTTTTTTTTTwwwwwwww',
      ],
    },
    // 11 ─ the march: take the blazon points, ring the bell
    {
      id: 'm11', rank: 3, theme: 'castle', title: 'The March on Blackmere', place: 'Blackmere walls', mapPos: [80, 48], weather: 'snow', kind: 'story',
      type: 'Siege', captive: [25, 9],
      intro: 'Snow on the road, and two hundred loyal men waiting in the woods for a signal. Blackmere\u2019s banners must come down before they march.\n\nTake the three blazon points (stand on each with no enemy close by), then ring the chapel bell in the inner yard. The King\u2019s men will pour in. Then take the captain of the keep.',
      outro: 'Blackmere falls by nightfall. The Prince\u2019s captains surrender their swords to a ragged band in Lincoln green.\n\nOnly the Sheriff remains, in his keep at Nottingham, sitting on the taxes of three shires. And the King\u2019s ransom is not yet paid.',
      heroes: { robin: [12, 26], john: [13, 26], marian: [11, 26], tuck: [14, 26], scarlet: [15, 26] }, need: ['robin'],
      exit: { x: 9, y: 25, w: 8, h: 3 },
      blazons: [[13, 20, 'The outer gate'], [3, 13, 'The west tower'], [24, 13, 'The east tower']],
      allies: [[12, 21], [13, 21], [14, 21], [15, 21], [12, 22], [15, 22]],
      props: [{ id: 'bell', kind: 'bell', x: 6, y: 3, say: 'The bell of Blackmere rings out across the snow! The King\u2019s men are coming.' }],
      objectives: ['blazons', 'use:bell', 'boss'],
      guards: [
        { boss: true, name: 'the captain of the keep', type: 'boss', route: [[14, 3, 0]], looks: [S, W, E] },
        { type: 'knight', route: [[13, 8, 0]], looks: [S] },
        { type: 'knight', route: [[14, 8, 0]], looks: [S] },
        { route: [[13, 19, 0]], looks: [S, S - 0.5, S + 0.5] },
        { route: [[14, 19, 0]], looks: [S, S + 0.5, S - 0.5] },
        { type: 'archer', route: [[3, 11, 0]], looks: [E, S] },
        { route: [[2, 16, 2], [8, 16, 2]] },
        { type: 'archer', route: [[24, 11, 0]], looks: [W, S] },
        { route: [[25, 16, 2], [19, 16, 2]] },
        { type: 'officer', route: [[6, 10, 1], [21, 10, 1]] },
        { type: 'halberd', route: [[4, 4, 0]], looks: [E, S] },
        { route: [[19, 2, 2], [24, 5, 2]] },
      ],
      gold: [[1, 9, 20], [26, 9, 20], [2, 4, 20]],
      treasure: { id: 'crown', name: 'the Crown of Ravenscar', x: 26, y: 4 },
      reward: 110,
      tips: [
        { id: 'snow', when: 'start', text: 'Snow muffles everything. Stand on a glowing blazon point with no enemy close by and count to three to raise our colours.' },
        { id: 'allies', when: 'used:bell', text: 'The King\u2019s men (green tabards) fight on their own. Let them carry the battle while you go for the captain.' },
      ],
      map: [
        '############################',
        '#rrrrrr#ffffffffffff#rrrrrr#',
        '#rrrrrr#ffffffffffff#rrrrrr#',
        '#ffffffffffffffffffffffffff#',
        '#ffffffffffffffffffffffffff#',
        '#ffccffffffffffffffffffhhff#',
        '#ffffffffffffffffffffffffff#',
        '#############ff#############',
        '#ffffffffffffffffffffffffff#',
        '#ffffffffffffffffffffffffff#',
        '#ffffffffffffffffffffffffff#',
        '#ffffffrrrrffffffrrrrffffff#',
        '#ffhfffrrrrffffffrrrrfffhff#',
        '#ffffffrrrrffffffrrrrffffff#',
        '#ffffffffffffffffffffffffff#',
        '#ffccffffffffffffffffffccff#',
        '#ffffffffffffffffffffffffff#',
        '#ffffffffffffffffffffffffff#',
        '############ffff############',
        'TT..b.......,,,,.......b..TT',
        'TT..........,,,,..........TT',
        'TTT...b.....,,,,.....b...TTT',
        'TTT.........,,,,.........TTT',
        'TTTT..T.....,,,,.....T..TTTT',
        'TTTT........,,,,........TTTT',
        'TTTTTb......,,,,......bTTTTT',
        'TTTTTT......,,,,......TTTTTT',
        'TTTTTTTT............TTTTTTTT',
        'TTTTTTTTTTTTTTTTTTTTTTTTTTTT',
      ],
    },
    // 12 ─ the final challenge
    {
      id: 'm12', rank: 3, theme: 'castle', title: 'The Last Arrow', place: 'The Sheriff\u2019s keep', mapPos: [67, 50], night: true, kind: 'story',
      type: 'Final challenge', climbs: [[6, 20, 6, 18]], needRansom: true,
      intro: 'The ransom is paid, and King Richard is on the road home. One debt is left to settle.\n\nThe band goes in from two sides: Robin, Marian and Will by the moat, John and Tuck from the hay cart already inside the lower yard. Capture the Sheriff alive and tie him up, take the tax chest from the treasury, and get everyone out over the moat.',
      outro: 'The Sheriff, trussed like a Michaelmas goose, is left on the abbey steps with a note pinned to his cloak, in a hand that every child in the shire now knows.\n\nThe taxes go home. The King comes home. And somewhere in Sherwood an arrow is fitted to a string, just in case.',
      heroes: { robin: [14, 25], marian: [13, 25], scarlet: [12, 25], john: [2, 15], tuck: [3, 15] }, need: ['robin', 'john'],
      exit: { x: 10, y: 23, w: 8, h: 3 },
      chest: { x: 2, y: 10 },
      sheriff: { x: 14, y: 3 },
      objectives: ['sheriff', 'steal', 'exit'],
      reinforce: [[14, 18, 'knight'], [15, 18, 'soldier'], [13, 17, 'archer']],
      torches: [[13, 7], [16, 7], [10, 15], [19, 15], [11, 18], [16, 18], [6, 2], [23, 2], [8, 9]],
      guards: [
        { type: 'knight', route: [[5, 5, 2], [24, 5, 2]] },
        { type: 'black', route: [[12, 7, 0]], looks: [S, S - 0.6, S + 0.4] },
        { type: 'black', route: [[17, 7, 0]], looks: [S, S + 0.6, S - 0.4] },
        { route: [[9, 14, 1], [20, 14, 1], [20, 17, 1], [9, 17, 1]] },
        { type: 'halberd', route: [[12, 18, 0]], looks: [S, S - 0.5, S] },
        { route: [[15, 18, 0]], looks: [S, S + 0.5, S] },
        { type: 'officer', route: [[4, 10, 0]], looks: [E, E - 0.6, E + 0.6] },
        { route: [[4, 17, 3], [10, 17, 3]] },
        { type: 'archer', route: [[24, 7, 2], [28, 7, 2], [28, 16, 2]] },
        { type: 'black', route: [[22, 3, 0]], looks: [W, S] },
      ],
      gold: [[27, 9, 20], [1, 12, 20], [5, 2, 25], [24, 12, 15]],
      reward: 150,
      tips: [
        { id: 'split', when: 'start', text: 'Two groups: John and Tuck start inside the lower yard. Tap a portrait twice to select one group, or use \u{1F465} All.' },
        { id: 'sheriff', when: 'nearGuard', text: 'Black-cloaked guards hold their posts and won\u2019t chase you far. The Sheriff is tough: knock him out or beat him, then tie him up.' },
      ],
      map: [
        '##############################',
        '#rrrrrrrrrrrrrrrrrrrrrrrrrrrr#',
        '#rr#dddddddddddddddddddddd#rr#',
        '#rr#dddddddddddddddddddddd#rr#',
        '#rr#dd##dddddddddddddd##dd#rr#',
        '#rr#dddddddddddddddddddddd#rr#',
        '#rr##########dddd#####dd###rr#',
        '#ffffffffffffffffffffffffffff#',
        '#########ffffffffffff#########',
        '#fffffff#ffffffffffff#hhfffff#',
        '#ffffffffffffffffffffffffffff#',
        '#fffffff#ffffffffffff#fffffff#',
        '#fffffff#ffffwwwwffff#ccfffff#',
        '#########ffffwwwwffff#########',
        '#ffffffffffffffffffffffffffff#',
        '#fhhff##ffffffffffffff##ffhff#',
        '#ffffffffffffffffffffffffffff#',
        '#ccfffffffffffffffffffffffccf#',
        '#ffffffffffffffffffffffffffff#',
        '##f#########ffff##############',
        'TT..b.......,,,,.......b...TTT',
        'TT,wwwwwwwww,,,,wwwwwwwwwwwwTT',
        'TT.....b....,,,,....b......TTT',
        'TTT.........,,,,.........TTTTT',
        'TTTTb.......,,,,.......bTTTTTT',
        'TTTTTT......,,,,......TTTTTTTT',
        'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
      ],
    },
  ];
  RH.MISSIONS.forEach((m, i) => { m.idx = i; });
})(window.RH);
