// The story campaign: sixteen missions in the order of the original game's campaign
// (see rh_ref/spec/missions/). GENERATED by tools/campaign.py: edit that, then run `python3 tools/campaign.py`.
// All mission names, maps and text are original. Legend figures and English towns are public domain.
'use strict';
(function (RH) {
  RH.MISSIONS = [
 {
  "id": "m1",
  "rank": 0,
  "theme": "castle",
  "title": "The Steward’s Kitchen",
  "place": "Lincoln castle",
  "town": "Lincoln",
  "kind": "story",
  "horn": false,
  "type": "Find an ally",
  "climbs": [
   [
    14,
    17,
    14,
    15
   ]
  ],
  "intro": "Home from the Crusade, Robin of Locksley finds his lands seized and his name on a warrant. His one friend in Lincoln, Sir Aldous, has not been seen for a week; only old Wat, his steward, might know why.\n\nWat works the castle kitchen now. Get over the wall, find him, and keep out of the guards’ green sight. Beggars hear everything; a coin may loosen a tongue.",
  "outro": "Gisela wipes the flour from her hands. “Sir Aldous was taken in the night. And they will hang your old lieutenant, Will Stutely, at Nottingham’s gallows cross on market day.”\n\nRobin pulls up his hood. Sherwood, then, and Nottingham after.",
  "heroes": {
   "robin": [
    6,
    18
   ]
  },
  "need": [
   "robin"
  ],
  "coach": {
   "walk": [
    9,
    18
   ],
   "bush": [
    11,
    17
   ],
   "inside": [
    13,
    2,
    27,
    15
   ]
  },
  "exit": {
   "x": 19,
   "y": 29,
   "w": 4,
   "h": 2
  },
  "objectives": [
   "meet:wat",
   "meet:gisela",
   "exit"
  ],
  "contacts": [
   {
    "id": "wat",
    "name": "Old Wat",
    "x": 20,
    "y": 6,
    "look": 2,
    "say": "“Master Robin! They said you died in the Holy Land.” Wat drops his voice. “Sir Aldous is gone, taken by the Sheriff’s friends. My Gisela in the village below knows the rest. Go to her, and mind the drawbridge winch; it squeals.”",
    "reveals": [
     "gisela"
    ]
   },
   {
    "id": "gisela",
    "name": "Gisela",
    "x": 23,
    "y": 23,
    "look": 3,
    "hidden": true,
    "female": true,
    "say": "“So you’re the one Father talks about.”"
   }
  ],
  "beggars": [
   {
    "id": "b1",
    "x": 16,
    "y": 13,
    "price": 10,
    "pays": [
     "s1"
    ],
    "say": [
     "The steward? Feeds the guards in the kitchen, north side. The garden behind the hall has a purse in the roses, if you’re quick."
    ]
   }
  ],
  "scrolls": [
   {
    "id": "s1",
    "x": 25,
    "y": 10,
    "hidden": true,
    "gold": 20,
    "text": "Tucked in the rose bed: a purse and a note. “The drawbridge winch stands by the gate. Pull it and the bridge comes down.”"
   }
  ],
  "props": [
   {
    "id": "t1",
    "kind": "target",
    "x": 14,
    "y": 8,
    "lure": [
     "yard"
    ],
    "to": [
     24,
     14
    ],
    "label": "🎯 Shoot the archery target",
    "say": "“Oh, a lovely shot!” The bowmen wander off to argue about it."
   },
   {
    "id": "t2",
    "kind": "target",
    "x": 14,
    "y": 10,
    "lure": [
     "yard"
    ],
    "to": [
     24,
     14
    ],
    "label": "🎯 Shoot the archery target",
    "say": "“Oh, a lovely shot!” The bowmen wander off to argue about it."
   },
   {
    "id": "bridge",
    "kind": "lever",
    "x": 22,
    "y": 15,
    "gate": [
     [
      20,
      16
     ],
     [
      21,
      16
     ],
     [
      20,
      17
     ],
     [
      21,
      17
     ],
     [
      20,
      18
     ],
     [
      21,
      18
     ]
    ],
    "say": "The drawbridge thunders down over the moat."
   }
  ],
  "guards": [
   {
    "route": [
     [
      17,
      9,
      0
     ]
    ],
    "type": "soldier",
    "looks": [
     3.141592653589793,
     2.741592653589793,
     3.441592653589793
    ],
    "tag": "yard"
   },
   {
    "route": [
     [
      17,
      11,
      0
     ]
    ],
    "type": "archer",
    "looks": [
     3.141592653589793,
     3.541592653589793,
     3.141592653589793
    ],
    "tag": "yard"
   },
   {
    "route": [
     [
      19,
      7,
      2
     ],
     [
      26,
      7,
      2
     ]
    ]
   },
   {
    "route": [
     [
      15,
      22,
      2
     ],
     [
      19,
      22,
      1
     ],
     [
      19,
      27,
      2
     ],
     [
      15,
      26,
      1
     ]
    ]
   },
   {
    "route": [
     [
      24,
      19,
      0
     ]
    ],
    "type": "soldier",
    "looks": [
     1.5707963267948966,
     1.0707963267948966,
     0.0,
     1.5707963267948966
    ]
   }
  ],
  "civilians": [
   [
    16,
    25
   ],
   [
    8,
    23
   ],
   [
    26,
    19
   ]
  ],
  "gold": [
   [
    2,
    23,
    10
   ],
   [
    27,
    28,
    15
   ],
   [
    13,
    14,
    10
   ]
  ],
  "clovers": [
   [
    27,
    12
   ]
  ],
  "reward": 30,
  "tips": [
   {
    "id": "pause",
    "when": "time40",
    "text": "Tip: tap ⏸ any time to stop the clock. You can still give orders while paused, then tap Resume."
   }
  ],
  "map": [
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
   "TT.T..TT.TT.#################T",
   "T....T.....T#################T",
   "T..TT......T#,rrr,,,rrrrrrr,#T",
   "T.T..TTT.T.T#,rrr,,,rrrrrrr,#T",
   "T.TT........#,rrr,,,rrrrrrr,#T",
   "TT.....T..TT#,,,,,,,,,,,,,,,#T",
   "T..T.TTT..T.#,,,,,,,,,,,,,,,#T",
   "TT.T....TT.T#,,,,,,,,,,,,,,,#T",
   "TTT.TT.T..T.#,,,,,,,,,,,bbbb#T",
   "T.......T.TT#,,,,,,,,,,,b.bb#T",
   "T...TT.T..T.#h,,,,,,,,,,bbbb#T",
   "T..T..TT..T.#h,,,,,,,,,,,,,,#T",
   "T.TTTT.TT.T.#ddd,,,,,,,,,,cc#T",
   "T.TT.TTT.TTT#ddd,,,,,,,,,,,c#T",
   "T.T.TT...rr.#ddd,,,,,,,,,,,,#T",
   "TT..TT...rrT########ff#######T",
   "T..........bb....wwwddwwwwwwwT",
   "T................wwwddwwwwwwww",
   "T........b..w.......,,.......T",
   "T.rrr.....b.w..rrr..,,.......T",
   "T.rrr...b...w..rrr..,,..rrr..T",
   "T........b..w.......,,..rrr..T",
   "T...........w.....b.,,.......T",
   "T...,,,,,,,,d,,,,,,,,,.b...h.T",
   "T...........w....m..,,h......T",
   "T.....rrr...w.b.....,,..rrr..T",
   "T.....rrr...w..rrr..,,..rrr..T",
   "T.rr........w..rrr..,,.......T",
   "T.rr........w.......,,.....b.T",
   "T....b......w.......,,.......T",
   "TTTTTTTTTTTTTTTTTTTT,,TTTTTTTT"
  ],
  "mapPos": [
   66,
   33
  ]
 },
 {
  "id": "m2",
  "rank": 1,
  "theme": "town",
  "title": "The Gallows Cross",
  "place": "Nottingham market",
  "town": "Nottingham",
  "kind": "story",
  "type": "Public rescue",
  "captive": [
   15,
   12
  ],
  "intro": "At noon the Sheriff hangs Will Stutely and two of Robin’s old company at the gallows cross in Nottingham market.\n\nThe gate guards are lazy and one is asleep: walk in quietly. Five soldiers stand round the gallows. A purse thrown where they can all see it starts a brawl.",
  "outro": "Stutely rubs his neck. “That rope was tighter than my wife’s purse strings.” The freed men melt into the crowd and out through the gate.\n\nThat night the camp in Sherwood has two more mouths to feed, and every one of them can tie a knot.",
  "heroes": {
   "robin": [
    15,
    30
   ]
  },
  "need": [
   "robin"
  ],
  "exit": {
   "x": 12,
   "y": 31,
   "w": 6,
   "h": 2
  },
  "prisoners": [
   {
    "id": "stutely",
    "x": 14,
    "y": 12
   }
  ],
  "objectives": [
   "free:stutely",
   "exit"
  ],
  "guards": [
   {
    "route": [
     [
      13,
      24,
      0
     ]
    ],
    "type": "soldier",
    "looks": [
     1.5707963267948966,
     0.9707963267948966,
     1.5707963267948966
    ]
   },
   {
    "route": [
     [
      16,
      24,
      0
     ]
    ],
    "type": "soldier",
    "looks": [
     1.5707963267948966,
     2.1707963267948966,
     1.5707963267948966
    ],
    "watch": true
   },
   {
    "route": [
     [
      21,
      11,
      0
     ]
    ],
    "type": "soldier",
    "looks": [
     3.141592653589793,
     2.641592653589793,
     1.5707963267948966
    ]
   },
   {
    "route": [
     [
      12,
      11,
      0
     ]
    ],
    "looks": [
     1.5707963267948966,
     1.1707963267948966
    ]
   },
   {
    "route": [
     [
      17,
      11,
      0
     ]
    ],
    "looks": [
     1.5707963267948966,
     1.9707963267948965
    ]
   },
   {
    "route": [
     [
      12,
      14,
      0
     ]
    ],
    "looks": [
     0.0,
     0.4
    ]
   },
   {
    "route": [
     [
      17,
      14,
      0
     ]
    ],
    "looks": [
     3.141592653589793,
     2.741592653589793
    ]
   },
   {
    "route": [
     [
      11,
      16,
      1
     ],
     [
      11,
      9,
      1
     ]
    ]
   },
   {
    "route": [
     [
      9,
      8,
      1
     ],
     [
      20,
      8,
      1
     ]
    ],
    "type": "officer"
   },
   {
    "route": [
     [
      14,
      4,
      0
     ]
    ],
    "type": "knight",
    "looks": [
     1.5707963267948966,
     1.0707963267948966,
     2.0707963267948966
    ],
    "purse": 25
   }
  ],
  "nobles": [
   [
    16,
    4
   ]
  ],
  "civilians": [
   [
    13,
    17
   ],
   [
    18,
    20
   ],
   [
    7,
    22
   ],
   [
    24,
    22
   ],
   [
    4,
    11
   ]
  ],
  "beggars": [
   {
    "id": "b1",
    "x": 9,
    "y": 27,
    "price": 10,
    "pays": [
     "s1"
    ],
    "say": [
     "Stutely? They’ll string him up at noon. The guards round the gallows love money more than they love each other."
    ]
   }
  ],
  "scrolls": [
   {
    "id": "s1",
    "x": 4,
    "y": 6,
    "hidden": true,
    "gold": 25,
    "text": "On the roof-ladder of a west-side house, a purse and a scrawl: “The church knight carries the Sheriff’s tithe.”"
   }
  ],
  "gold": [
   [
    25,
    4,
    15
   ],
   [
    3,
    22,
    10
   ],
   [
    26,
    26,
    10
   ]
  ],
  "clovers": [
   [
    24,
    3
   ]
  ],
  "reward": 40,
  "tips": [
   {
    "id": "purse",
    "when": "start",
    "text": "Robin fights with a sword, so a fight kills. Knock guards out from behind instead, or toss a 💰 purse where several can see it: they brawl over it."
   }
  ],
  "map": [
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
   "T############################T",
   "T#rrr,rr,############,#######T",
   "T#rrr,rr,#dddddddddd#,#ffff##T",
   "T#rrr,rr,#dddddddddd#,#ffff##T",
   "T#,,,,,,,#dddddddddd#,#ffff##T",
   "T#,,,,,,,#dddddddddd#,#ffff##T",
   "T#rrr,,,,#####ff#####,#ffff##T",
   "T#rrr,,,,,,,,,,,,,,,,,#ffff##T",
   "T#rrr,,,,,m,,x,,x,,m,,##f####T",
   "T#,,,,,,,,ffffffffff,,,,,,,,#T",
   "T#,,,,,,,,ffffffffff,,,,,,,,#T",
   "T#rrrrrrr,ffffffffff,,rrr,rr#T",
   "T#rrrrrrr,ffffffffff,,rrr,rr#T",
   "T#rrrrrrr,ffffffffff,,rrr,rr#T",
   "T#,,,,,,,,ffffffffff,c,,,,,,#T",
   "T#,,,,,,,c,,,,,,,,,,,c,,,,,,#T",
   "T#rrr,rrr,rrr,,,,rrr,,rrr,rr#T",
   "T#rrr,rrr,rrr,,,,rrr,,rrr,rr#T",
   "T#rrr,rrr,rrr,,,,rrr,,rrr,rr#T",
   "T#,,,,,,,,,,,,,,,,,,,,,,,,rr#T",
   "T#,h,c,,,,,h,,,,,,,h,,,,,c,,#T",
   "T#,,,,,,,,,,,,,,,,,,,,,,,,,,#T",
   "T#############,,#############T",
   "T....b.T....T.,,...T.........T",
   "TT............,,......T..T.b.T",
   "T.....T.......,,.TT....b.b...T",
   "TT...T.T......,,...T....T....T",
   "T....T.T......,,.T...........T",
   "T..........T..,,..b.bb......bT",
   "T....T........,,.............T",
   "T.............,,...b....T..T.T",
   "T...Tb....bT..,,....T.T..b...T",
   "TTTTTTTTTTTTTT,,TTTTTTTTTTTTTT"
  ],
  "mapPos": [
   55,
   56
  ]
 },
 {
  "id": "m3",
  "rank": 2,
  "theme": "castle",
  "title": "Lanterns at Leicester",
  "place": "Leicester castle",
  "mapPos": [
   64,
   69
  ],
  "night": true,
  "kind": "story",
  "type": "Night rescue",
  "captive": [
   7,
   3
  ],
  "climbs": [
   [
    11,
    18,
    11,
    16
   ]
  ],
  "intro": "Will Scarlet, the quickest blade in the shire, waits in a cell at Leicester for the hangman’s cart.\n\nThe walls are lit with lanterns. Guards see less far in the dark, but anyone in lantern light is plain to see. Robin can scale the wall at the rope mark and let a rope down for Stutely. Archers on the walls shoot from afar.",
  "outro": "Will Scarlet rubs his wrists, then grins and draws a sling from his boot. “They took my sword. They didn’t think to take this.”\n\nA sling, a short temper and a quick blade: the band is three. In Nottingham, a message waits for Robin at the chapel of St Anne.",
  "heroes": {
   "robin": [
    13,
    24
   ],
   "stutely": [
    14,
    24
   ]
  },
  "need": [
   "robin"
  ],
  "exit": {
   "x": 9,
   "y": 23,
   "w": 10,
   "h": 3
  },
  "prisoners": [
   {
    "id": "scarlet",
    "x": 17,
    "y": 2
   }
  ],
  "objectives": [
   "free:scarlet",
   "exit"
  ],
  "torches": [
   [
    9,
    5
   ],
   [
    19,
    5
   ],
   [
    13,
    9
   ],
   [
    3,
    12
   ],
   [
    24,
    12
   ],
   [
    20,
    16
   ],
   [
    21,
    18
   ],
   [
    17,
    18
   ]
  ],
  "guards": [
   {
    "route": [
     [
      19,
      18,
      0
     ]
    ],
    "looks": [
     1.5707963267948966,
     2.0707963267948966,
     1.5707963267948966,
     0.9707963267948966
    ]
   },
   {
    "route": [
     [
      21,
      18,
      0
     ]
    ],
    "looks": [
     1.5707963267948966,
     1.0707963267948966,
     1.5707963267948966,
     2.1707963267948966
    ]
   },
   {
    "type": "archer",
    "route": [
     [
      3,
      15,
      3,
      0
     ],
     [
      9,
      15,
      3,
      3.141592653589793
     ]
    ]
   },
   {
    "route": [
     [
      8,
      12,
      1
     ],
     [
      19,
      12,
      1
     ],
     [
      19,
      6,
      1
     ],
     [
      8,
      6,
      1
     ]
    ]
   },
   {
    "route": [
     [
      12,
      5,
      2,
      -1.5707963267948966
     ],
     [
      21,
      5,
      2,
      -1.5707963267948966
     ]
    ]
   },
   {
    "type": "archer",
    "route": [
     [
      25,
      9,
      0
     ]
    ],
    "looks": [
     3.141592653589793,
     2.541592653589793,
     3.741592653589793
    ]
   },
   {
    "route": [
     [
      24,
      15,
      2
     ],
     [
      24,
      6,
      2
     ]
    ]
   },
   {
    "type": "officer",
    "route": [
     [
      16,
      3,
      0
     ]
    ],
    "looks": [
     1.5707963267948966,
     3.141592653589793,
     1.5707963267948966,
     0
    ]
   }
  ],
  "gold": [
   [
    6,
    2,
    20
   ],
   [
    21,
    3,
    20
   ],
   [
    2,
    10,
    15
   ],
   [
    24,
    20,
    15
   ]
  ],
  "reward": 60,
  "tips": [
   {
    "id": "night",
    "when": "start",
    "text": "Night: guards see less far in the dark, but torchlight gives you away. Bushes and hay hide you unless a guard is right beside you."
   },
   {
    "id": "climb",
    "when": "time6",
    "text": "Tap the rope mark on the wall with Robin to climb it. Once he’s over, the others can climb too."
   },
   {
    "id": "archer",
    "when": "nearGuard",
    "text": "Archers shoot from a distance once they’ve seen you. Close in fast, or keep out of their sight."
   }
  ],
  "map": [
   "############################",
   "#rrrrrrrrrrrrrrrrrrrrrrrrrr#",
   "#rrr#ffff#ffff#ffff#ffff#rr#",
   "#rrr#ffff#ffff#ffff#ffff#rr#",
   "#rrr##ff###ff###ff###ff##rr#",
   "#ffffffffffffffffffffffffff#",
   "#ffffffffffffffffffffffffff#",
   "#ffhhfff##ffffffffff##ffhhf#",
   "#fffffff##ffffffffff##fffff#",
   "#ffffffffffffffffffffffffff#",
   "#ffccfffffffwwwwfffffffccff#",
   "#fffffffffffwwwwfffffffffff#",
   "#ffffffffffffffffffffffffff#",
   "#fffffff##ffffffffff##fffff#",
   "#ffhffff##ffffffffff##ffhff#",
   "#ffffffffffffffffffffffffff#",
   "#ffffffffffffffffffffffffff#",
   "#####ff############ff#######",
   "TT..b,,...........b,,.....TT",
   "TTwww,,wwwwwwwwwwwww,,wwwwTT",
   "TT...,,.....bb.....,,....bTT",
   "TTT..,,..T.........,,..T.TTT",
   "TTTb.,,,,,,,,,,,,,,,,....TTT",
   "TTTT..........,.......bTTTTT",
   "TTTTTb........,........TTTTT",
   "TTTTTTT.......,......TTTTTTT",
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTT"
  ],
  "town": "Leicester"
 },
 {
  "id": "m4",
  "rank": 3,
  "theme": "town",
  "title": "Vespers",
  "place": "Nottingham, St Mary’s",
  "mapPos": [
   55,
   56
  ],
  "night": true,
  "kind": "story",
  "type": "Beggars’ trail",
  "captive": [
   22,
   14
  ],
  "intro": "A note in a lady’s hand: “At vespers, St Anne’s. Come alone, or come quietly.” No name, only a pressed rose.\n\nThe chapel is somewhere in the back streets, and the Sheriff’s men are thick on the ground. Follow the beggars: each knows a little, and each will point you to the next. Gentlemen out late will run for the watch if they see you.",
  "outro": "Lady Marian of Leaford lowers her hood. “The Sheriff dines at my father’s table and talks too much. I can be your eyes in his house.”\n\nShe has heard that Prince John meets his barons at Derby castle in three days. Whatever he plans, the outlaws mean to hear it.\n\nMarian will not come to Sherwood, not yet: she is more use to the band with the Sheriff’s ear.",
  "heroes": {
   "robin": [
    10,
    25
   ],
   "stutely": [
    11,
    25
   ],
   "scarlet": [
    12,
    25
   ]
  },
  "need": [
   "robin"
  ],
  "exit": {
   "x": 7,
   "y": 24,
   "w": 8,
   "h": 3
  },
  "objectives": [
   "meet:marian",
   "exit"
  ],
  "contacts": [
   {
    "id": "marian",
    "name": "the hooded lady",
    "x": 10,
    "y": 5,
    "hidden": true,
    "female": true,
    "say": "“You took your time, Robin of Locksley.”"
   }
  ],
  "beggars": [
   {
    "id": "b1",
    "x": 6,
    "y": 21,
    "price": 10,
    "pays": [
     "b2"
    ],
    "say": [
     "St Anne’s? Old Mother Brede by the tannery yard knows the way. Look east, past the fountain."
    ]
   },
   {
    "id": "b2",
    "x": 22,
    "y": 9,
    "hidden": true,
    "price": 15,
    "pays": [
     "s1",
     "b3"
    ],
    "say": [
     "A lady in a grey hood, yes. She left something in the cooper’s yard. Then ask Lame Tom by the west wall."
    ]
   },
   {
    "id": "b3",
    "x": 3,
    "y": 10,
    "hidden": true,
    "price": 10,
    "pays": [
     "marian"
    ],
    "say": [
     "The chapel lies north, behind the high wall. She is inside, at the altar. Mind the watchman at the door."
    ]
   }
  ],
  "scrolls": [
   {
    "id": "s1",
    "x": 12,
    "y": 15,
    "hidden": true,
    "gold": 10,
    "item": [
     "apples",
     3
    ],
    "text": "A basket of apples and a note: “A guard who hears a thump behind him always turns to look.” Throw an apple (Will Scarlet) to turn a guard’s head."
   }
  ],
  "torches": [
   [
    11,
    8
   ],
   [
    7,
    11
   ],
   [
    17,
    11
   ],
   [
    11,
    21
   ],
   [
    2,
    15
   ],
   [
    23,
    15
   ],
   [
    14,
    3
   ]
  ],
  "guards": [
   {
    "type": "halberd",
    "route": [
     [
      11,
      8,
      0
     ]
    ],
    "looks": [
     1.5707963267948966,
     0.9707963267948966,
     2.1707963267948966
    ]
   },
   {
    "type": "officer",
    "route": [
     [
      7,
      11,
      2
     ],
     [
      22,
      11,
      2
     ]
    ]
   },
   {
    "route": [
     [
      2,
      12,
      2
     ],
     [
      2,
      17,
      2
     ]
    ]
   },
   {
    "route": [
     [
      23,
      20,
      2
     ],
     [
      23,
      12,
      2
     ]
    ]
   },
   {
    "route": [
     [
      7,
      2,
      1
     ],
     [
      14,
      2,
      1
     ],
     [
      14,
      8,
      1
     ],
     [
      7,
      8,
      1
     ]
    ]
   },
   {
    "route": [
     [
      8,
      20,
      2
     ],
     [
      17,
      20,
      2
     ]
    ]
   }
  ],
  "nobles": [
   [
    12,
    13
   ],
   [
    16,
    21
   ]
  ],
  "gold": [
   [
    2,
    22,
    10
   ],
   [
    23,
    5,
    15
   ],
   [
    23,
    18,
    10
   ]
  ],
  "treasure": {
   "id": "cup",
   "name": "the Abbot’s silver cup",
   "x": 22,
   "y": 2
  },
  "reward": 60,
  "tips": [
   {
    "id": "chain",
    "when": "start",
    "text": "Follow the trail of beggars. Pay each one and a new beggar, parchment or person appears. Look for the gold rings on the map."
   },
   {
    "id": "apple",
    "when": "time30",
    "text": "Will Scarlet: 🍎 Apple turns one guard’s head toward where it lands. 🪨 Sling knocks a guard out from six tiles away."
   }
  ],
  "map": [
   "TTTTTTTTTTTTTTTTTTTTTTTTTT",
   "T########################T",
   "T#rrrr.ffffffff.rrrrr...#T",
   "T#rrrr.f######f.rrrrr...#T",
   "T#rrrr.f#dddd#f.rrrrr...#T",
   "T#.....f#dddd#f.........#T",
   "T#.h...f#dddd#f....h....#T",
   "T#rrr..f##dd##f..rrrrr..#T",
   "T#rrr..ffffffff..rrrrr..#T",
   "T#rrr..f......f..rrrrr..#T",
   "T#.....f.rrrr.f.........#T",
   "T#ffffff.rrrr.ffffffffff#T",
   "T#f......rrrr..........f#T",
   "T#f.rrr..........rrrr..f#T",
   "T#f.rrr..cc..h...rrrr..f#T",
   "T#f.rrr..........rrrr..f#T",
   "T#f.......rrrrr........f#T",
   "T#ffffff..rrrrr..ffffff.#T",
   "T#rrrr.f..rrrrr..f.rrrr.#T",
   "T#rrrr.f.........f.rrrr.#T",
   "T#rrrr.ffffffffff..rrrr.#T",
   "T#.........f..........h.#T",
   "T#.c.rrrr..f..rrrrr.....#T",
   "T#...rrrr..f..rrrrr..c..#T",
   "T#####.....f......#######T",
   "TTTTT......,......TTTTTTTT",
   "TTTTTT....,,,....TTTTTTTTT",
   "TTTTTTTTTTTTTTTTTTTTTTTTTT"
  ],
  "town": "Nottingham"
 },
 {
  "id": "m5",
  "rank": 4,
  "theme": "castle",
  "title": "The Prince’s Council",
  "place": "Derby castle",
  "mapPos": [
   30,
   50
  ],
  "weather": "fog",
  "kind": "story",
  "type": "Eavesdrop",
  "captive": [
   26,
   10
  ],
  "climbs": [
   [
    6,
    20,
    6,
    18
   ]
  ],
  "intro": "Prince John has called his barons to Derby castle. Fog lies thick on the moat: a gift from God, says a friar’s cousin, who sold us the plan of the hall.\n\nReach the listening gallery at the east end of the great hall and stand there unseen until you have heard enough. Knights in great helms guard the Prince: arrows glance off them. Halberdiers won’t stoop for coins.",
  "outro": "“…and while my brother rots in an Austrian prison, his ransom will rot in my treasury.”\n\nKing Richard is alive and held for ransom, and the Prince means to keep him there. The outlaws will raise the ransom themselves, one stolen purse at a time. Pay into the King’s Ransom chest at camp.",
  "heroes": {
   "robin": [
    14,
    25
   ],
   "stutely": [
    15,
    25
   ],
   "marian": [
    13,
    25
   ],
   "scarlet": [
    12,
    25
   ]
  },
  "need": [
   "robin",
   "marian"
  ],
  "exit": {
   "x": 10,
   "y": 23,
   "w": 8,
   "h": 3
  },
  "objectives": [
   "listen:gallery",
   "exit"
  ],
  "props": [
   {
    "id": "gallery",
    "kind": "listen",
    "x": 24,
    "y": 5,
    "dur": 5,
    "say": "The Prince’s voice carries: “Let Richard’s ransom gather dust. By Michaelmas the crown is mine.” You have heard enough."
   }
  ],
  "nobles": [
   [
    14,
    3
   ],
   [
    10,
    4
   ],
   [
    18,
    3
   ]
  ],
  "guards": [
   {
    "type": "knight",
    "route": [
     [
      12,
      2,
      0
     ]
    ],
    "looks": [
     1.5707963267948966,
     0,
     1.5707963267948966
    ]
   },
   {
    "type": "knight",
    "route": [
     [
      20,
      5,
      2
     ],
     [
      5,
      5,
      2
     ]
    ]
   },
   {
    "type": "halberd",
    "route": [
     [
      13,
      7,
      0
     ]
    ],
    "looks": [
     1.5707963267948966,
     0.9707963267948966,
     1.9707963267948965
    ]
   },
   {
    "type": "halberd",
    "route": [
     [
      16,
      7,
      0
     ]
    ],
    "looks": [
     1.5707963267948966,
     2.1707963267948966,
     1.1707963267948966
    ]
   },
   {
    "route": [
     [
      9,
      14,
      1
     ],
     [
      20,
      14,
      1
     ],
     [
      20,
      17,
      1
     ],
     [
      9,
      17,
      1
     ]
    ]
   },
   {
    "route": [
     [
      12,
      18,
      0
     ]
    ],
    "looks": [
     1.5707963267948966,
     1.0707963267948966,
     1.5707963267948966
    ]
   },
   {
    "type": "archer",
    "route": [
     [
      4,
      10,
      0
     ]
    ],
    "looks": [
     0,
     -0.6,
     0.6
    ]
   },
   {
    "route": [
     [
      1,
      14,
      3,
      1.5707963267948966
     ],
     [
      1,
      18,
      3,
      -1.5707963267948966
     ]
    ]
   },
   {
    "type": "officer",
    "route": [
     [
      24,
      7,
      2
     ],
     [
      28,
      7,
      2
     ],
     [
      28,
      16,
      2
     ]
    ]
   }
  ],
  "gold": [
   [
    27,
    9,
    20
   ],
   [
    1,
    12,
    20
   ],
   [
    5,
    2,
    25
   ],
   [
    24,
    12,
    15
   ]
  ],
  "treasure": {
   "id": "seal",
   "name": "the Great Seal of the barons",
   "x": 25,
   "y": 2
  },
  "reward": 80,
  "tips": [
   {
    "id": "fog",
    "when": "start",
    "text": "Fog: everyone sees a shorter way. Use it to cross the open bailey."
   },
   {
    "id": "listen",
    "when": "nearProp",
    "text": "Stand on the listening spot and stay still. If anyone sees you, you lose what you’ve heard so far."
   }
  ],
  "map": [
   "##############################",
   "#rrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
   "#rr#dddddddddddddddddddddd#rr#",
   "#rr#dddddddddddddddddddddd#rr#",
   "#rr#dd##dddddddddddddd##dd#rr#",
   "#rr#dddddddddddddddddddddd#rr#",
   "#rr##########dddd#####dd###rr#",
   "#ffffffffffffffffffffffffffff#",
   "#########ffffffffffff#########",
   "#fffffff#ffffffffffff#hhfffff#",
   "#ffffffffffffffffffffffffffff#",
   "#fffffff#ffffffffffff#fffffff#",
   "#fffffff#ffffwwwwffff#ccfffff#",
   "#########ffffwwwwffff#########",
   "#ffffffffffffffffffffffffffff#",
   "#ffhff##ffffffffffffff##ffhff#",
   "#ffffffffffffffffffffffffffff#",
   "#ccfffffffffffffffffffffffccf#",
   "#ffffffffffffffffffffffffffff#",
   "##f#########ffff##############",
   "TT..b.......,,,,.......b...TTT",
   "TT,wwwwwwwww,,,,wwwwwwwwwwwwTT",
   "TT.....b....,,,,....b......TTT",
   "TTT.........,,,,.........TTTTT",
   "TTTTb.......,,,,.......bTTTTTT",
   "TTTTTT......,,,,......TTTTTTTT",
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT"
  ],
  "town": "Derby"
 },
 {
  "id": "m6",
  "rank": 5,
  "theme": "forest",
  "title": "Smoke over Wychwood",
  "place": "Wychwood village",
  "town": "Sherwood",
  "kind": "story",
  "staff": true,
  "type": "Village liberation",
  "intro": "The Sheriff’s men are burning Wychwood for unpaid taxes. They have caught a giant of a man who tried to stop them, and they mean to hang him at the crossroads.\n\nThis is forest work: Robin carries a quarterstaff today, so every blow knocks out instead of killing. Five soldiers block the west road where the old folk want to flee, and an execution is being readied in the north-east.",
  "outro": "The giant shakes off the last rope. “John Little, they call me, or Little John to wits like you.” He grins. “You fight well for a small man.”\n\nSherwood has its strongest arm. And the villagers of Wychwood will remember who came when the smoke rose.",
  "heroes": {
   "robin": [
    16,
    29
   ],
   "stutely": [
    17,
    29
   ],
   "scarlet": [
    15,
    29
   ]
  },
  "need": [
   "robin"
  ],
  "exit": {
   "x": 15,
   "y": 29,
   "w": 3,
   "h": 2
  },
  "prisoners": [
   {
    "id": "john",
    "x": 16,
    "y": 6
   }
  ],
  "captive": [
   25,
   4
  ],
  "objectives": [
   "free:john",
   "exit"
  ],
  "triggers": [
   {
    "id": "shack",
    "x": 14,
    "y": 4,
    "w": 5,
    "h": 4,
    "reinforce": [
     [
      19,
      6,
      "knight"
     ]
    ],
    "say": "A knight bursts out of the shack!"
   }
  ],
  "guards": [
   {
    "route": [
     [
      5,
      17,
      0
     ]
    ],
    "looks": [
     0.0,
     0.4
    ]
   },
   {
    "route": [
     [
      6,
      15,
      0
     ]
    ],
    "looks": [
     0.0,
     -0.3
    ]
   },
   {
    "route": [
     [
      7,
      18,
      0
     ]
    ],
    "looks": [
     0.0
    ]
   },
   {
    "route": [
     [
      4,
      16,
      0
     ]
    ],
    "type": "archer",
    "looks": [
     0.0,
     0.5
    ]
   },
   {
    "route": [
     [
      8,
      16,
      0
     ]
    ],
    "type": "officer",
    "looks": [
     0.0,
     -0.6,
     0.6
    ]
   },
   {
    "route": [
     [
      15,
      14,
      0
     ]
    ],
    "looks": [
     1.5707963267948966,
     1.0707963267948966
    ]
   },
   {
    "route": [
     [
      18,
      15,
      0
     ]
    ],
    "looks": [
     3.141592653589793,
     3.541592653589793
    ]
   },
   {
    "route": [
     [
      15,
      18,
      0
     ]
    ],
    "type": "archer",
    "looks": [
     1.5707963267948966,
     0.0
    ]
   },
   {
    "route": [
     [
      15,
      8,
      0
     ]
    ],
    "type": "archer",
    "looks": [
     1.5707963267948966,
     1.9707963267948965
    ]
   },
   {
    "route": [
     [
      17,
      8,
      0
     ]
    ],
    "looks": [
     1.5707963267948966,
     1.1707963267948966
    ]
   },
   {
    "route": [
     [
      16,
      4,
      0
     ]
    ],
    "looks": [
     1.5707963267948966,
     2.0707963267948966
    ]
   },
   {
    "route": [
     [
      23,
      4,
      0
     ]
    ],
    "type": "archer",
    "looks": [
     0.0,
     0.3
    ]
   },
   {
    "route": [
     [
      24,
      6,
      0
     ]
    ],
    "type": "archer",
    "looks": [
     -1.5707963267948966,
     -1.1707963267948966
    ]
   },
   {
    "route": [
     [
      26,
      6,
      0
     ]
    ],
    "type": "officer",
    "looks": [
     3.141592653589793,
     -1.5707963267948966
    ]
   },
   {
    "route": [
     [
      20,
      16,
      2
     ],
     [
      29,
      16,
      2
     ]
    ]
   },
   {
    "route": [
     [
      16,
      20,
      3
     ],
     [
      16,
      26,
      3
     ]
    ],
    "type": "knight",
    "purse": 20
   }
  ],
  "civilians": [
   [
    14,
    25
   ],
   [
    12,
    22
   ],
   [
    19,
    22
   ],
   [
    10,
    14
   ],
   [
    27,
    15
   ]
  ],
  "beggars": [
   {
    "id": "b1",
    "x": 28,
    "y": 17,
    "price": 10,
    "pays": [
     "s1"
    ],
    "say": [
     "They’ve got a giant tied by the old shack, north road. Mind the archers either side of him, they’d shoot their own mothers."
    ]
   }
  ],
  "scrolls": [
   {
    "id": "s1",
    "x": 26,
    "y": 11,
    "hidden": true,
    "gold": 30,
    "text": "Under the woodpile: the reeve’s hidden rent money, and a note in his hand: “The giant’s staff is on the shack roof.”"
   }
  ],
  "gold": [
   [
    18,
    3,
    25
   ],
   [
    3,
    14,
    10
   ],
   [
    27,
    8,
    15
   ],
   [
    11,
    27,
    10
   ]
  ],
  "clovers": [
   [
    28,
    26
   ]
  ],
  "reward": 50,
  "tips": [
   {
    "id": "staff",
    "when": "start",
    "text": "Forest work: Robin carries a staff today, so his blows knock out instead of killing. Clear the five soldiers on the west road to let the old folk escape."
   }
  ],
  "map": [
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
   "T....b.T...TTT..,,...TT.TTTTb.bT",
   "T....bTb..bT....,,............TT",
   "TTTb.TTTT.T.....,,.rrx.x.x.x.T.T",
   "TTT.TTTT.T.T....,,.rr.h.......TT",
   "TT.T.T..TT.T....,,.......l.....T",
   "T..TTT...T......,,.........h.b.T",
   "T.T..T....T.....,,...........TTT",
   "T....T.T........,,...TT.TTT..T.T",
   "T..TT.T.........,,.......bT.TT.T",
   "T.TTT........b..,,......rrT..b.T",
   "TT.....T...rr...,,..rr.Trr.....T",
   "T.TT.T..rr.rr...,,..rr..T..T...T",
   "T.T.Tb.Trr....l.,,......hT.T.T.T",
   "TT...........h..,,.h...........T",
   "T.............b.,,.............T",
   "T,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,T",
   "T,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,T",
   "T...............,,.............T",
   "T..........rrh..,,l......T....TT",
   "T.......T..rr...,,..rrr...TT...T",
   "TTT.....Tb...b..,,..rrr..T.TT..T",
   "TTT..bT.T.....b.,,........T.TT.T",
   "TTT..TTT.TT.....,,..T..TTTTTTT.T",
   "T....T..TTb.....,,..T..T.T.bTTbT",
   "T..TT.......T...,,........T..TTT",
   "TT.T.TTT..TT....,,..b.TTTT.T.b.T",
   "TT..T...TT..T...,,...T...TTTT..T",
   "T..T.T.T...TT...,,..T.T.T.T..T.T",
   "TTTTT..T.TT.....,,...T..T.TT.TTT",
   "TT.TTbT..bT.T...,,...TTTTTT....T",
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT"
  ],
  "mapPos": [
   47,
   47
  ]
 },
 {
  "id": "m7",
  "rank": 6,
  "theme": "castle",
  "title": "A Word at Dusk",
  "place": "Leicester castle",
  "town": "Leicester",
  "kind": "story",
  "night": true,
  "type": "Courier, no killing",
  "intro": "Prince John means to have Lord Aubrey of Leicester quietly murdered: the old lord is too loyal to the King. Marian has learned it, and she will take Robin to him.\n\nNo blood tonight. If a single soldier dies, the lord will never trust an outlaw. Marian can walk among guards, and she can listen at a door to learn who waits inside.",
  "outro": "Lord Aubrey hears them out in silence, then unbuckles his sword and lays it on the table. “When the King’s men march, Leicester marches with them.”\n\nMarian slips back to her father’s house before the bells. Robin takes the river road home, richer by a friend.",
  "heroes": {
   "robin": [
    5,
    14
   ],
   "marian": [
    6,
    14
   ],
   "stutely": [
    5,
    15
   ],
   "scarlet": [
    6,
    15
   ]
  },
  "need": [
   "robin",
   "marian"
  ],
  "exit": {
   "x": 4,
   "y": 13,
   "w": 3,
   "h": 3
  },
  "contacts": [
   {
    "id": "aubrey",
    "name": "Lord Aubrey",
    "x": 25,
    "y": 5,
    "look": 2,
    "needs": "robin",
    "say": "“Robin of Locksley? In my own hall?” The old lord listens, then grips Robin’s arm. “Then the Prince is a traitor, and I am the King’s man.”"
   }
  ],
  "objectives": [
   "meet:aubrey",
   "nokill",
   "exit"
  ],
  "treasure": {
   "id": "roll",
   "name": "the Shire Roll",
   "x": 16,
   "y": 23
  },
  "torches": [
   [
    13,
    13
   ],
   [
    13,
    16
   ],
   [
    18,
    10
   ],
   [
    25,
    9
   ],
   [
    16,
    18
   ],
   [
    22,
    15
   ],
   [
    8,
    12
   ],
   [
    8,
    17
   ]
  ],
  "guards": [
   {
    "route": [
     [
      10,
      13,
      0
     ]
    ],
    "looks": [
     3.141592653589793,
     3.641592653589793
    ]
   },
   {
    "route": [
     [
      8,
      8,
      2
     ],
     [
      8,
      21,
      2
     ]
    ]
   },
   {
    "route": [
     [
      15,
      13,
      0
     ]
    ],
    "type": "soldier",
    "looks": [
     3.141592653589793,
     1.5707963267948966
    ]
   },
   {
    "route": [
     [
      15,
      16,
      0
     ]
    ],
    "type": "halberd",
    "looks": [
     3.141592653589793,
     -1.5707963267948966
    ]
   },
   {
    "route": [
     [
      17,
      11,
      1
     ],
     [
      26,
      11,
      1
     ],
     [
      26,
      18,
      1
     ],
     [
      17,
      18,
      1
     ]
    ]
   },
   {
    "route": [
     [
      18,
      7,
      0
     ]
    ],
    "type": "knight",
    "looks": [
     1.5707963267948966,
     2.0707963267948966
    ]
   },
   {
    "route": [
     [
      19,
      6,
      0
     ]
    ],
    "type": "soldier",
    "looks": [
     1.5707963267948966
    ]
   },
   {
    "route": [
     [
      25,
      9,
      0
     ]
    ],
    "type": "halberd",
    "looks": [
     1.5707963267948966,
     1.1707963267948966,
     1.9707963267948965
    ]
   },
   {
    "route": [
     [
      16,
      21,
      0
     ]
    ],
    "looks": [
     1.5707963267948966,
     0.0
    ]
   },
   {
    "route": [
     [
      17,
      23,
      0
     ]
    ],
    "type": "archer",
    "looks": [
     -1.5707963267948966,
     0.0
    ]
   },
   {
    "route": [
     [
      23,
      17,
      0
     ]
    ],
    "type": "officer",
    "looks": [
     3.141592653589793,
     1.5707963267948966,
     -1.5707963267948966
    ]
   }
  ],
  "civilians": [
   [
    20,
    14
   ],
   [
    24,
    16
   ],
   [
    19,
    19
   ],
   [
    27,
    21
   ],
   [
    21,
    24
   ],
   [
    9,
    27
   ]
  ],
  "nobles": [
   [
    22,
    10
   ]
  ],
  "beggars": [
   {
    "id": "b1",
    "x": 21,
    "y": 16,
    "price": 15,
    "pays": [
     "s1",
     "s2"
    ],
    "say": [
     "The old lord sups alone in the east hall. Soldiers drink in the chapel, mind. And the west tower holds something the Prince wants badly."
    ]
   }
  ],
  "scrolls": [
   {
    "id": "s1",
    "x": 27,
    "y": 24,
    "hidden": true,
    "gold": 40,
    "text": "A steward’s strongbox, badly hidden. “The chapel is full of the Prince’s soldiers: go round it.”"
   },
   {
    "id": "s2",
    "x": 15,
    "y": 18,
    "hidden": true,
    "gold": 0,
    "text": "Chalked on the tower door: “The Roll of the Shire, by order of the Prince, to be kept under guard.”"
   }
  ],
  "gold": [
   [
    11,
    21,
    15
   ],
   [
    26,
    14,
    20
   ],
   [
    6,
    28,
    10
   ]
  ],
  "clovers": [
   [
    11,
    28
   ]
  ],
  "reward": 60,
  "tips": [
   {
    "id": "nokill",
    "when": "start",
    "text": "No killing tonight: swords strike with the flat of the blade. Marian walks freely among guards, so send her ahead to look."
   }
  ],
  "map": [
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
   "Twww.........................T",
   "Twww.b......b################T",
   "Twww....b....#fffffffff######T",
   "Twww.rrr.rrr.#ff######f#ddd##T",
   "Twww.rrr.rrr.#ff#dddd#f#ddd##T",
   "Twww.rrr.rrr.#ff#dddd#f#ddd##T",
   "Twww.b.......#ff#dddd#f#ddd##T",
   "Twww.........#ff#dddd#f##f###T",
   "Twww.rrr.rrr.#ff##ff##ffffff#T",
   "Twww.rrr.rrr.#ffffffffffffhf#T",
   "Twwwb........#fcffffffffffff#T",
   "Twww.........#fcffffffrrrrrr#T",
   "Twwwddd......#ffffffffrrrrrr#T",
   "Twwwddd,,,,,,fffffffffrrrfff#T",
   "Twwwddd,,,,,,ffffffmffffffff#T",
   "Twww.........#ffffffffffffff#T",
   "Twww.........#hffffffmfffffc#T",
   "Twww.rrrbrrr.#ffffffffffffff#T",
   "Twww.rrr.rrr.###f##fffffffff#T",
   "Twww.rrr.rrr.##ddd#frrrfffff#T",
   "Twww.......b.##ddd#frrrfrrrf#T",
   "Twww.........##ddd#frrrfrrrf#T",
   "Twww.rrr.b..b##ddd#fffffrrrf#T",
   "Twww.rrr.rrr.##ddd#fffffffff#T",
   "Twww.....rrr.######fffffffff#T",
   "Twww..b......################T",
   "Twww........b................T",
   "Twww....brr..................T",
   "Twww.....rr.b................T",
   "Twww.........................T",
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT"
  ],
  "mapPos": [
   64,
   69
  ]
 },
 {
  "id": "m8",
  "rank": 7,
  "theme": "castle",
  "title": "Old Godric’s Cell",
  "place": "Lincoln castle",
  "town": "Lincoln",
  "kind": "story",
  "night": true,
  "type": "Dungeon rescue, then clear",
  "climbs": [
   [
    27,
    12,
    25,
    12
   ]
  ],
  "intro": "Sir Aldous’s men found him at last: in the cells under Lincoln castle, with Old Godric, Robin’s godfather, beside him.\n\nThe north-east wall is thick with ivy: everyone but Little John can climb it. Lower the drawbridge for John from inside. Free Godric, and his household guard will rise. Then knock out every one of the Prince’s men in the castle.",
  "outro": "Lincoln is taken without a single trumpet. Godric’s men bar the gates, and the Prince’s captain is sent home on a mule, facing backwards.\n\nBut the Prince will want Lincoln back. Scouts say his men are already on the road.",
  "heroes": {
   "robin": [
    15,
    28
   ],
   "john": [
    16,
    28
   ],
   "stutely": [
    14,
    28
   ],
   "scarlet": [
    17,
    28
   ],
   "marian": [
    13,
    28
   ]
  },
  "need": [
   "robin"
  ],
  "exit": {
   "x": 13,
   "y": 28,
   "w": 4,
   "h": 2
  },
  "contacts": [
   {
    "id": "godric",
    "name": "Old Godric",
    "x": 8,
    "y": 5,
    "look": 1,
    "say": "“Robin, lad! I knew you would come.” Godric beats on the wall: “Up, my lads! For Lincoln!” His men break out of the west range.",
    "allies": [
     [
      9,
      9
     ],
     [
      10,
      9
     ],
     [
      11,
      10
     ],
     [
      20,
      9
     ],
     [
      21,
      9
     ]
    ],
    "reinforce": [
     [
      21,
      7,
      "knight"
     ],
     [
      22,
      7,
      "knight"
     ]
    ],
    "reinforceSay": "Two knights come out of the chapel!"
   }
  ],
  "objectives": [
   "meet:godric",
   {
    "k": "clear",
    "after": "godric",
    "text": "Knock out every one of the Prince’s men"
   }
  ],
  "props": [
   {
    "id": "bridge",
    "kind": "lever",
    "x": 17,
    "y": 19,
    "gate": [
     [
      15,
      20
     ],
     [
      16,
      20
     ],
     [
      15,
      21
     ],
     [
      16,
      21
     ],
     [
      15,
      22
     ],
     [
      16,
      22
     ]
    ],
    "say": "The drawbridge comes down. Little John can come in."
   }
  ],
  "triggers": [
   {
    "id": "walk",
    "x": 13,
    "y": 10,
    "w": 7,
    "h": 2,
    "reinforce": [
     [
      8,
      17,
      "soldier"
     ],
     [
      7,
      17,
      "archer"
     ],
     [
      23,
      17,
      "soldier"
     ],
     [
      24,
      17,
      "soldier"
     ]
    ],
    "say": "Guy the castellan spots you from the hall and runs, shouting for the tower guards!"
   }
  ],
  "torches": [
   [
    15,
    19
   ],
   [
    9,
    9
   ],
   [
    21,
    9
   ],
   [
    13,
    13
   ],
   [
    19,
    16
   ],
   [
    24,
    12
   ],
   [
    6,
    12
   ]
  ],
  "guards": [
   {
    "route": [
     [
      15,
      19,
      0
     ]
    ],
    "looks": [
     1.5707963267948966,
     1.1707963267948966
    ]
   },
   {
    "route": [
     [
      17,
      18,
      0
     ]
    ],
    "type": "halberd",
    "looks": [
     1.5707963267948966,
     1.9707963267948965
    ]
   },
   {
    "route": [
     [
      7,
      12,
      2
     ],
     [
      24,
      12,
      2
     ]
    ]
   },
   {
    "route": [
     [
      9,
      9,
      0
     ]
    ],
    "type": "soldier",
    "looks": [
     1.5707963267948966,
     0.0
    ]
   },
   {
    "route": [
     [
      11,
      6,
      0
     ]
    ],
    "type": "archer",
    "looks": [
     3.141592653589793,
     1.5707963267948966
    ]
   },
   {
    "route": [
     [
      16,
      13,
      0
     ]
    ],
    "type": "officer",
    "looks": [
     -1.5707963267948966,
     1.5707963267948966,
     0.0,
     3.141592653589793
    ]
   },
   {
    "route": [
     [
      11,
      16,
      1
     ],
     [
      20,
      16,
      1
     ]
    ]
   },
   {
    "route": [
     [
      23,
      10,
      0
     ]
    ],
    "type": "archer",
    "looks": [
     3.141592653589793,
     1.5707963267948966
    ]
   },
   {
    "route": [
     [
      16,
      7,
      0
     ]
    ],
    "type": "soldier",
    "looks": [
     1.5707963267948966,
     2.1707963267948966
    ]
   }
  ],
  "gold": [
   [
    24,
    4,
    30
   ],
   [
    7,
    4,
    20
   ],
   [
    28,
    4,
    10
   ],
   [
    3,
    28,
    10
   ]
  ],
  "clovers": [
   [
    19,
    6
   ]
  ],
  "reward": 70,
  "tips": [
   {
    "id": "ivy",
    "when": "start",
    "text": "Climb the ivy on the north-east wall (Little John is too heavy). Pull the drawbridge winch inside the gate to let him in."
   }
  ],
  "map": [
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
   "TTT..TT..T..T....TT............T",
   "T....######################T...T",
   "T....########,rrr,#########..T.T",
   "TTTT.##ddddd#,rrr,#dddddd##....T",
   "T....##ddddd#,rrr,#dddddd##.T.TT",
   "T....##ddddd#,,,,,#dddddd##T...T",
   "T....##ddddd#,,,,,#dddddd##..TTT",
   "T..T.####f###,,,,,###ff####.TTTT",
   "T....#,,,,,,,,,,,,,,,,,,,,#TT.TT",
   "T....#,,,,,,,b.....b,,,,,,#..T.T",
   "T....#,,,,,,,bbbbbbb,,,,,,#....T",
   "T....#,,,,,,,,,,,,,,,,,,,,#....T",
   "T..T.#,,,,,cc,,,,,,,,,,,,,#...TT",
   "T.T..#,,,,,,,,,,,,,c,,,,,,#....T",
   "T....#####,,,,,,,,,,,,#####TT.TT",
   "T....##dd#,,,,,,,,,,,,#dd##..TTT",
   "TTTT.##ddf,,,,,,,,,,,,fdd##T...T",
   "T....##dd#,,,,hh,,,,,,#dd##....T",
   "T....#####,,,,,,,,,,,,#####....T",
   "T....##########ff##########.T..T",
   "TwwwwwwwwwwwwwwddwwwwwwwwwwwwwwT",
   "T....wwwwwwwwwwddwwwwwwwwww....T",
   "T..rrr.....rr..,,.......rrr..T.T",
   "TTbrrrT.T.Trr.T,,T....TTrrrTT.bT",
   "TT.......T..b..,,...b.....T..b.T",
   "T...,,,,,,,,,,,,,,,,,,,,,,,,...T",
   "T........T.b...,,.....b........T",
   "TT..bT..rrr....,,.T.rrr........T",
   "T.......rrr...T,,...rrr.......bT",
   "T.T....bbT.T...,,.......bb.T.T.T",
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT"
  ],
  "mapPos": [
   66,
   33
  ]
 },
 {
  "id": "m9",
  "rank": 8,
  "theme": "castle",
  "title": "The Hanging Cage",
  "place": "Derby inner yard",
  "mapPos": [
   30,
   50
  ],
  "night": true,
  "kind": "story",
  "type": "Cage rescue",
  "captive": [
   2,
   4
  ],
  "intro": "Friar Tuck preached against the Prince on Derby’s market cross. Now he hangs in an iron cage over the inner yard, singing hymns loudly enough to annoy the whole garrison.\n\nThe moat is too wide to swim. Shoot through the rope that holds the drawbridge plank. Inside, work the winch to lower the cage, then cut Tuck out.",
  "outro": "“My knees,” groans Tuck, “were not made for cages.” Then, brightening: “But I know a brewer in Sherwood who owes me a favour, and my bees will be missing me.”\n\nTuck brings his ale and his beehives to camp. Set men to the brewery and the skeps.",
  "heroes": {
   "robin": [
    12,
    22
   ],
   "john": [
    13,
    22
   ],
   "stutely": [
    11,
    22
   ],
   "scarlet": [
    14,
    22
   ]
  },
  "need": [
   "robin"
  ],
  "exit": {
   "x": 9,
   "y": 21,
   "w": 8,
   "h": 3
  },
  "prisoners": [
   {
    "id": "tuck",
    "x": 13,
    "y": 11,
    "cage": "winch"
   }
  ],
  "objectives": [
   "free:tuck",
   "listen:council",
   "exit"
  ],
  "props": [
   {
    "id": "plankT",
    "kind": "target",
    "x": 9,
    "y": 16,
    "plank": [
     [
      12,
      17
     ],
     [
      12,
      18
     ]
    ],
    "label": "🎯 Shoot the plank rope"
   },
   {
    "id": "winch",
    "kind": "winch",
    "x": 20,
    "y": 5
   },
   {
    "id": "council",
    "kind": "listen",
    "x": 22,
    "y": 3,
    "dur": 5,
    "say": "Behind the shutters the Prince’s steward counts aloud: “A hundred thousand marks for the King’s ransom, and not a penny of it raised. Let Austria keep him.”"
   }
  ],
  "torches": [
   [
    5,
    14
   ],
   [
    20,
    14
   ],
   [
    13,
    10
   ],
   [
    4,
    4
   ],
   [
    21,
    4
   ],
   [
    12,
    3
   ]
  ],
  "guards": [
   {
    "route": [
     [
      12,
      12,
      0
     ]
    ],
    "looks": [
     1.5707963267948966,
     3.141592653589793,
     1.5707963267948966
    ]
   },
   {
    "route": [
     [
      14,
      12,
      0
     ]
    ],
    "looks": [
     1.5707963267948966,
     0,
     1.5707963267948966
    ]
   },
   {
    "route": [
     [
      4,
      14,
      0
     ]
    ],
    "looks": [
     1.5707963267948966,
     0.9707963267948966,
     0
    ]
   },
   {
    "route": [
     [
      21,
      14,
      0
     ]
    ],
    "looks": [
     1.5707963267948966,
     2.1707963267948966,
     3.141592653589793
    ]
   },
   {
    "type": "archer",
    "route": [
     [
      3,
      10,
      2
     ],
     [
      8,
      10,
      2
     ]
    ]
   },
   {
    "type": "officer",
    "route": [
     [
      18,
      4,
      1
     ],
     [
      23,
      4,
      1
     ],
     [
      23,
      11,
      1
     ],
     [
      18,
      11,
      1
     ]
    ]
   },
   {
    "route": [
     [
      2,
      3,
      2
     ],
     [
      8,
      3,
      2
     ]
    ]
   },
   {
    "type": "halberd",
    "route": [
     [
      21,
      5,
      0
     ]
    ],
    "looks": [
     3.141592653589793,
     1.5707963267948966,
     -1.5707963267948966
    ]
   }
  ],
  "gold": [
   [
    1,
    13,
    15
   ],
   [
    24,
    13,
    15
   ],
   [
    12,
    2,
    20
   ]
  ],
  "reward": 70,
  "tips": [
   {
    "id": "plank",
    "when": "start",
    "text": "The plank bridge is tied up on the far bank. Select Robin or Marian, tap 🏹 Bow, then tap the target post to cut the rope."
   },
   {
    "id": "winch",
    "when": "nearProp",
    "text": "The winch creaks: guards nearby will come to look. Clear them away first."
   }
  ],
  "map": [
   "##########################",
   "#rrrrrrrr#ffffff#rrrrrrrr#",
   "#rrrrrrrr#ffffff#rrrrrrrr#",
   "#ffffffff#ffffff#ffffffff#",
   "#ffhhffffffffffffffffccff#",
   "#ffffffffffffffffffffffff#",
   "#fffccffff######fffffffff#",
   "#ffffffff#rrrrrr#ffffhhff#",
   "#ffffffff#rrrrrr#ffffffff#",
   "#ffffffff#rrrrrr#ffffffff#",
   "#ffffffffffffffffffffffff#",
   "#ffccfffffffffffffffccfff#",
   "#ffffffffffffffffffffffff#",
   "#ffffhfffffffffffffffffff#",
   "#ffffffffffffffffffhhffff#",
   "####ff##############ff####",
   "T.b.,,.....b.........,,.TT",
   "wwwwwwwwwwwwwwwwwwwwwwwwww",
   "wwwwwwwwwwwwwwwwwwwwwwwwww",
   "T.b..........b......b...TT",
   "T.........,,,,.........TTT",
   "TT.......,,,,,,.......TTTT",
   "TTb......,,,,,,......bTTTT",
   "TTT.......,,,,.......TTTTT",
   "TTTTT......,,......TTTTTTT",
   "TTTTTTTTTTTTTTTTTTTTTTTTTT"
  ],
  "town": "Derby"
 },
 {
  "id": "m10",
  "rank": 9,
  "theme": "castle",
  "title": "The Black Castle",
  "place": "Derby castle",
  "town": "Derby",
  "kind": "story",
  "type": "Siege: take the blazons",
  "intro": "Lord Aubrey’s men are camped in the woods below Derby’s black walls, but they will not throw themselves at the gate. Every banner you pull down tells them the way is clear, and they advance.\n\nTake each blazon point (stand on it with no enemy near). The castellan, Sir Roger Mallory, holds the high tower and will not come down: beat him in a duel there. If it goes badly, step out, heal and go back in.",
  "outro": "Sir Roger yields his sword on the tower stair. Aubrey’s banner goes up over Derby, and the townsfolk, who hated Sir Roger rather more than they loved anybody, cheer the outlaws in the street.\n\nThe Prince will try to take it back. He always does.",
  "heroes": {
   "robin": [
    14,
    29
   ],
   "john": [
    15,
    29
   ],
   "stutely": [
    13,
    29
   ],
   "scarlet": [
    16,
    29
   ],
   "tuck": [
    12,
    29
   ]
  },
  "need": [
   "robin"
  ],
  "exit": {
   "x": -9,
   "y": -9,
   "w": 1,
   "h": 1
  },
  "blazons": [
   [
    14,
    22,
    "The outer gate"
   ],
   [
    23,
    17,
    "The north-east yard"
   ],
   [
    14,
    10,
    "The north yard"
   ],
   [
    14,
    6,
    "The high tower"
   ]
  ],
  "allies": [
   [
    13,
    27
   ],
   [
    14,
    27
   ],
   [
    15,
    27
   ],
   [
    13,
    26
   ],
   [
    15,
    26
   ],
   [
    14,
    25
   ],
   [
    12,
    26
   ],
   [
    16,
    26
   ],
   [
    13,
    25
   ],
   [
    15,
    25
   ],
   [
    12,
    27
   ],
   [
    16,
    27
   ]
  ],
  "allyWave": 3,
  "objectives": [
   "blazons",
   "boss"
  ],
  "guards": [
   {
    "route": [
     [
      13,
      23,
      0
     ]
    ],
    "type": "halberd",
    "looks": [
     1.5707963267948966,
     1.1707963267948966
    ]
   },
   {
    "route": [
     [
      16,
      23,
      0
     ]
    ],
    "type": "halberd",
    "looks": [
     1.5707963267948966,
     1.9707963267948965
    ]
   },
   {
    "route": [
     [
      5,
      18,
      2
     ],
     [
      19,
      18,
      2
     ]
    ]
   },
   {
    "route": [
     [
      6,
      13,
      1
     ],
     [
      18,
      13,
      1
     ]
    ],
    "type": "officer"
   },
   {
    "route": [
     [
      8,
      21,
      0
     ]
    ],
    "type": "archer",
    "looks": [
     1.5707963267948966,
     0.0
    ]
   },
   {
    "route": [
     [
      20,
      21,
      0
     ]
    ],
    "type": "archer",
    "looks": [
     1.5707963267948966,
     3.141592653589793
    ]
   },
   {
    "route": [
     [
      22,
      14,
      0
     ]
    ],
    "type": "archer",
    "looks": [
     3.141592653589793,
     1.5707963267948966
    ]
   },
   {
    "route": [
     [
      24,
      19,
      0
     ]
    ],
    "type": "archer",
    "looks": [
     3.141592653589793,
     -1.5707963267948966
    ]
   },
   {
    "route": [
     [
      23,
      15,
      0
     ]
    ],
    "type": "soldier",
    "looks": [
     3.141592653589793
    ]
   },
   {
    "route": [
     [
      10,
      9,
      0
     ]
    ],
    "looks": [
     1.5707963267948966,
     0.0
    ]
   },
   {
    "route": [
     [
      19,
      9,
      0
     ]
    ],
    "looks": [
     1.5707963267948966,
     3.141592653589793
    ]
   },
   {
    "route": [
     [
      14,
      11,
      0
     ]
    ],
    "type": "officer",
    "looks": [
     1.5707963267948966,
     0.9707963267948966,
     2.1707963267948966
    ]
   },
   {
    "route": [
     [
      10,
      5,
      0
     ]
    ],
    "type": "knight",
    "looks": [
     0.0,
     1.5707963267948966
    ]
   },
   {
    "route": [
     [
      19,
      5,
      0
     ]
    ],
    "type": "black",
    "looks": [
     3.141592653589793,
     1.5707963267948966
    ]
   },
   {
    "route": [
     [
      14,
      7,
      0
     ]
    ],
    "type": "boss",
    "looks": [
     1.5707963267948966,
     1.0707963267948966,
     2.0707963267948966
    ],
    "boss": true,
    "name": "Sir Roger Mallory"
   }
  ],
  "gold": [
   [
    4,
    4,
    25
   ],
   [
    25,
    4,
    25
   ],
   [
    23,
    19,
    20
   ],
   [
    13,
    6,
    40
   ]
  ],
  "clovers": [
   [
    5,
    23
   ]
  ],
  "treasure": {
   "id": "orb",
   "name": "the Orb of Derby",
   "x": 16,
   "y": 6
  },
  "reward": 80,
  "tips": [
   {
    "id": "blazon",
    "when": "start",
    "text": "Stand on a blazon (gold shield) with no enemy close by to raise our colours. Each one brings three of Aubrey’s men up to help."
   }
  ],
  "map": [
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
   "T...............T....T.T.....T",
   "TT.T...T.......T.....TT......T",
   "T..########################..T",
   "T..#,,,,##############,,,,#..T",
   "T.T#,,,,#fff######fff#,,,,#..T",
   "T..#,,,,#fff#dddd#fff#,,,,#..T",
   "TT.#,,,,#fff#dddd#fff#,,,,#..T",
   "T..#,,,,#fff##f###fff#,,,,#..T",
   "T..#,,,,#ffffffffffff#,,,,#..T",
   "TT.#,,,,#ffffffffffff#,,,,#..T",
   "T..#,,,,#ffffffffffff#,,,,#..T",
   "T..#h,,,######ff######,,,,#T.T",
   "T..#,,,c,,,,,,,,,,,,,######..T",
   "T..#rrr,,,,,,,,,,,,,,#hff##..T",
   "T..#rrr,,rrr,,,,rrr,,#fff##..T",
   "T..#rrr,,rrr,,,,rrr,,ffff##..T",
   "T..#,,,,,,,,,,,,,,,,,#fff##..T",
   "T.T#,,,,,,,,,c,,,,c,,#fff##..T",
   "T..#rrr,,rrr,,,,,,,,,#ffh##..T",
   "T..#rrr,,rrr,,,,,rrr,######..T",
   "T..#rrr,,rrr,,,,,rrr,,,,,,#..T",
   "TT.#,,,,,,,,,,,,,rrr,,,,,,#..T",
   "T..#,,,,,,,,,,,,,,,,,,,,,,#..T",
   "T..###########ff###########..T",
   "T.b...TT....b.,,.b......b....T",
   "T....T........,,.....Tb......T",
   "T.......T.....,,.......b...T.T",
   "T.............,,....b..T.T.T.T",
   "T..T...b......,,........T....T",
   "T.T....b.Tb...,,.b..T........T",
   "TTTTTTTTTTTTTT,,TTTTTTTTTTTTTT"
  ],
  "mapPos": [
   30,
   50
  ]
 },
 {
  "id": "m11",
  "rank": 10,
  "theme": "town",
  "title": "The Sheriff’s Tourney",
  "place": "Nottingham lists",
  "mapPos": [
   55,
   56
  ],
  "kind": "story",
  "type": "Archery contest",
  "captive": [
   24,
   18
  ],
  "intro": "The Sheriff offers an arrow of silver to the finest archer in England. Every fool in the shire knows it is bait for Robin Hood, and Robin is going anyway, in a borrowed hood.\n\nHit three targets. The aim sways: loose your arrow when the ring is steady. John and Tuck are hidden in the town in case it goes wrong.",
  "outro": "They found the silver arrow afterwards, still quivering in the Sheriff’s own chair. Nobody quite remembers how it got there.\n\nBut there is worse news. Sir Hugo de Vane, the Prince’s man, has claimed Marian’s hand. The wedding is at York minster, and it is tomorrow.",
  "heroes": {
   "robin": [
    13,
    10
   ]
  },
  "need": [
   "robin"
  ],
  "slots": 0,
  "exit": {
   "x": 8,
   "y": 24,
   "w": 12,
   "h": 3
  },
  "contest": {
   "need": 3
  },
  "prisoners": [
   {
    "id": "john",
    "x": 4,
    "y": 4,
    "friend": true,
    "name": "Little John"
   },
   {
    "id": "tuck",
    "x": 25,
    "y": 11,
    "friend": true,
    "name": "Friar Tuck"
   }
  ],
  "objectives": [
   "contest",
   "free:john",
   "free:tuck",
   "exit"
  ],
  "props": [
   {
    "id": "t1",
    "kind": "target",
    "contest": true,
    "x": 10,
    "y": 4
   },
   {
    "id": "t2",
    "kind": "target",
    "contest": true,
    "x": 13,
    "y": 4
   },
   {
    "id": "t3",
    "kind": "target",
    "contest": true,
    "x": 16,
    "y": 4
   }
  ],
  "guards": [
   {
    "route": [
     [
      6,
      5,
      0
     ]
    ],
    "looks": [
     0,
     -0.4
    ],
    "watch": true
   },
   {
    "route": [
     [
      21,
      5,
      0
     ]
    ],
    "looks": [
     3.141592653589793,
     3.541592653589793
    ],
    "watch": true
   },
   {
    "route": [
     [
      6,
      9,
      0
     ]
    ],
    "looks": [
     0
    ],
    "watch": true
   },
   {
    "route": [
     [
      21,
      9,
      0
     ]
    ],
    "looks": [
     3.141592653589793
    ],
    "watch": true
   },
   {
    "type": "officer",
    "route": [
     [
      13,
      13,
      0
     ]
    ],
    "looks": [
     -1.5707963267948966,
     -1.1707963267948966
    ],
    "watch": true
   },
   {
    "type": "archer",
    "route": [
     [
      4,
      13,
      0
     ]
    ],
    "looks": [
     0
    ],
    "watch": true
   },
   {
    "route": [
     [
      8,
      19,
      2
     ],
     [
      19,
      19,
      2
     ]
    ]
   },
   {
    "route": [
     [
      13,
      22,
      0
     ]
    ],
    "looks": [
     1.5707963267948966,
     -1.5707963267948966
    ]
   },
   {
    "type": "knight",
    "route": [
     [
      24,
      13,
      0
     ]
    ],
    "looks": [
     3.141592653589793,
     1.5707963267948966
    ]
   }
  ],
  "civilians": [
   [
    5,
    3
   ],
   [
    22,
    3
   ],
   [
    5,
    11
   ],
   [
    22,
    11
   ],
   [
    10,
    13
   ],
   [
    17,
    13
   ],
   [
    4,
    17
   ],
   [
    23,
    17
   ]
  ],
  "nobles": [
   [
    18,
    13
   ]
  ],
  "gold": [
   [
    1,
    22,
    15
   ],
   [
    26,
    22,
    15
   ],
   [
    2,
    18,
    10
   ]
  ],
  "treasure": {
   "id": "arrow",
   "name": "the Silver Arrow",
   "x": 14,
   "y": 3
  },
  "reward": 80,
  "tips": [
   {
    "id": "aim",
    "when": "start",
    "text": "Tap 🏹 Bow, then a target. Watch the swaying ring over it: Robin looses half a second after you tap, so tap when it is about to settle."
   },
   {
    "id": "sprung",
    "when": "sprung",
    "text": "Run! Find John (in the hay by the north-west stands) and Tuck (by the east stalls). Tap each to call him over, then everyone out the south gate."
   }
  ],
  "map": [
   "############################",
   "#rrrr..................rrrr#",
   "#rrrr..xxxxxxxxxxxxxx..rrrr#",
   "#......x............x......#",
   "#.hh...x............x...hh.#",
   "#......x............x......#",
   "#rrr...x............x...rrr#",
   "#rrr...x............x...rrr#",
   "#rrr...x............x...rrr#",
   "#......x............x......#",
   "#.mm...x............x...mm.#",
   "#......x............x......#",
   "#rrr...xxxxxx..xxxxxx...rrr#",
   "#rrr......................r#",
   "#.rrrr..ffffffffffff..rrrr.#",
   "#.rrrr..f..........f..rrrr.#",
   "#.rrrr..f..rrrrrr..f..rrrr.#",
   "#.......f..rrrrrr..f.......#",
   "#.h.....f..rrrrrr..f.....c.#",
   "#.......ffffffffffff.......#",
   "#rrrrr.......ff.......rrrrr#",
   "#rrrrr.......ff.......rrrrr#",
   "#.....b......ff......b.....#",
   "#######......ff......#######",
   "TTTTTT#......ff......#TTTTTT",
   "TTTTTT#..............#TTTTTT",
   "TTTTTTTT............TTTTTTTT",
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTT"
  ],
  "town": "Nottingham"
 },
 {
  "id": "m12",
  "rank": 11,
  "theme": "town",
  "title": "Bells for a Bride",
  "place": "York minster",
  "mapPos": [
   33,
   30
  ],
  "kind": "story",
  "type": "Wedding rescue",
  "captive": [
   26,
   19
  ],
  "intro": "The bells of York ring for a wedding nobody wants. Marian stands at the altar beside Sir Hugo de Vane, and half the Prince’s guard stands in the square.\n\nRaise the King’s banner over the east gate: every loyal Prince’s man in the square will run to tear it down. Then storm the church, free Marian and beat Sir Hugo. He is a master swordsman and won’t leave the church: retreat and heal if you must.",
  "outro": "Sir Hugo de Vane is found that evening, still tied to the bell rope, ringing every time he struggles.\n\nMarian is safe. But in the rush, Robin was taken at the church door and dragged to Nottingham gaol. Without him, the band must find its own way.",
  "heroes": {
   "robin": [
    12,
    28
   ],
   "john": [
    13,
    28
   ],
   "tuck": [
    14,
    28
   ],
   "scarlet": [
    15,
    28
   ]
  },
  "need": [
   "robin"
  ],
  "exit": {
   "x": 9,
   "y": 27,
   "w": 10,
   "h": 3
  },
  "prisoners": [
   {
    "id": "marian",
    "x": 2,
    "y": 2
   }
  ],
  "objectives": [
   "use:banner",
   "free:marian",
   "boss",
   "exit"
  ],
  "props": [
   {
    "id": "banner",
    "kind": "banner",
    "x": 26,
    "y": 8,
    "to": [
     22,
     9
    ],
    "lure": [
     "sq"
    ],
    "say": "The King’s lions fly over the east gate! The Prince’s men run to tear them down."
   }
  ],
  "guards": [
   {
    "boss": true,
    "name": "Sir Hugo de Vane",
    "type": "boss",
    "route": [
     [
      5,
      3,
      0
     ]
    ],
    "looks": [
     1.5707963267948966,
     0,
     1.5707963267948966
    ],
    "hp": 12
   },
   {
    "tag": "sq",
    "route": [
     [
      5,
      7,
      0
     ]
    ],
    "looks": [
     1.5707963267948966,
     1.0707963267948966
    ]
   },
   {
    "tag": "sq",
    "route": [
     [
      6,
      7,
      0
     ]
    ],
    "looks": [
     1.5707963267948966,
     2.0707963267948966
    ]
   },
   {
    "tag": "sq",
    "type": "officer",
    "route": [
     [
      9,
      11,
      2
     ],
     [
      24,
      11,
      2
     ]
    ]
   },
   {
    "tag": "sq",
    "route": [
     [
      10,
      8,
      1
     ],
     [
      24,
      8,
      1
     ],
     [
      24,
      15,
      1
     ],
     [
      10,
      15,
      1
     ]
    ]
   },
   {
    "tag": "sq",
    "route": [
     [
      24,
      15,
      1
     ],
     [
      10,
      15,
      1
     ],
     [
      10,
      8,
      1
     ],
     [
      24,
      8,
      1
     ]
    ]
   },
   {
    "tag": "sq",
    "type": "halberd",
    "route": [
     [
      16,
      13,
      0
     ]
    ],
    "looks": [
     1.5707963267948966,
     3.141592653589793,
     0
    ]
   },
   {
    "type": "knight",
    "route": [
     [
      8,
      3,
      0
     ]
    ],
    "looks": [
     3.141592653589793,
     1.5707963267948966
    ]
   },
   {
    "route": [
     [
      8,
      21,
      2
     ],
     [
      19,
      21,
      2
     ]
    ]
   },
   {
    "type": "archer",
    "route": [
     [
      13,
      25,
      0
     ]
    ],
    "looks": [
     3.141592653589793,
     -1.5707963267948966,
     0,
     -1.5707963267948966
    ]
   }
  ],
  "nobles": [
   [
    8,
    5
   ],
   [
    3,
    5
   ],
   [
    17,
    19
   ],
   [
    20,
    13
   ]
  ],
  "civilians": [
   [
    12,
    9
   ],
   [
    18,
    12
   ],
   [
    21,
    20
   ],
   [
    6,
    20
   ]
  ],
  "gold": [
   [
    5,
    16,
    15
   ],
   [
    26,
    20,
    15
   ],
   [
    2,
    9,
    15
   ]
  ],
  "reward": 90,
  "tips": [
   {
    "id": "banner",
    "when": "start",
    "text": "The banner is on the east gate (marked on the map). Get one man there unseen and tap it."
   },
   {
    "id": "boss",
    "when": "used:banner",
    "text": "Sir Hugo holds the church. Fight him with swipes: thrust (swipe up) can’t be blocked, parry (back-and-forth) leaves him open."
   }
  ],
  "map": [
   "############################",
   "#dddddddddd#rrrrrrrrrrrrrrr#",
   "#dddddddddd#rrrrrrrrrrrrrrr#",
   "#dddddddddd#...............#",
   "#dddddddddd#..rrrr...rrrr..#",
   "#dddddddddd#..rrrr...rrrr..#",
   "#####dd#####..rrrr...rrrr..#",
   "#....ff....................#",
   "#.b..ff..ffffffffffffffff..#",
   "#....ff..f..............f..#",
   "#rrr.ff..f..mm....mm....f..#",
   "#rrr.ffffffffffffffffffff..#",
   "#rrr.ff..f..............f..#",
   "#....ff..f..mm....mm....f..#",
   "#.h..ff..f..............f..#",
   "#....ff..ffffffffffffffff..#",
   "#rrrr..........hh......rrrr#",
   "#rrrr.....rrrrrr.......rrrr#",
   "#rrrr.....rrrrrr.......rrrr#",
   "#.........rrrrrr...........#",
   "#..c.....................c.#",
   "#rrrrr..ffffffffffff..rrrrr#",
   "#rrrrr..f..........f..rrrrr#",
   "#rrrrr..f..b....b..f..rrrrr#",
   "#.......f..........f.......#",
   "######..f..........f..######",
   "TTTTT#..ffffffffffff..#TTTTT",
   "TTTTT##.....ffff.....##TTTTT",
   "TTTTTTT#....ffff....#TTTTTTT",
   "TTTTTTTT............TTTTTTTT"
  ],
  "town": "York"
 },
 {
  "id": "m13",
  "rank": 12,
  "theme": "town",
  "title": "The Captain Taken",
  "place": "Nottingham gaol",
  "mapPos": [
   55,
   56
  ],
  "weather": "fog",
  "kind": "story",
  "type": "Escape",
  "captive": [
   8,
   2
  ],
  "climbs": [
   [
    5,
    10,
    5,
    8
   ]
  ],
  "intro": "Robin is in Nottingham gaol, and the Sheriff has sent to London for a hangman worthy of him.\n\nWithout Robin, Marian or Will can climb at the rope mark. The sergeant of the watch checks on his gate guard every round: if the man is missing, he rings the alarm. Charm him, slip past him, or leave him standing.",
  "outro": "“You took your time,” says Robin, which Marian points out is her line.\n\nIn the gaol office they find a sealed letter, taken from a royal messenger. It bears King Richard’s own seal, and it must reach the Queen Mother’s boatman at York’s river stairs before dawn.",
  "heroes": {
   "john": [
    12,
    26
   ],
   "marian": [
    11,
    26
   ],
   "tuck": [
    13,
    26
   ],
   "scarlet": [
    14,
    26
   ]
  },
  "need": [
   "marian"
  ],
  "exit": {
   "x": 9,
   "y": 25,
   "w": 8,
   "h": 2
  },
  "prisoners": [
   {
    "id": "robin",
    "x": 5,
    "y": 2
   }
  ],
  "objectives": [
   "free:robin",
   "exit"
  ],
  "guards": [
   {
    "tag": "gate",
    "route": [
     [
      12,
      10,
      0
     ]
    ],
    "looks": [
     1.5707963267948966,
     0.9707963267948966,
     2.1707963267948966
    ]
   },
   {
    "type": "officer",
    "name": "the sergeant",
    "check": [
     12,
     11,
     "gate"
    ],
    "route": [
     [
      7,
      12,
      1
     ],
     [
      12,
      11,
      2
     ],
     [
      18,
      12,
      1
     ],
     [
      12,
      11,
      2
     ]
    ]
   },
   {
    "route": [
     [
      3,
      5,
      2
     ],
     [
      22,
      5,
      2
     ]
    ]
   },
   {
    "type": "archer",
    "route": [
     [
      20,
      7,
      0
     ]
    ],
    "looks": [
     3.141592653589793,
     2.541592653589793,
     1.5707963267948966
    ]
   },
   {
    "route": [
     [
      6,
      6,
      0
     ]
    ],
    "looks": [
     -1.5707963267948966,
     3.141592653589793,
     0
    ]
   },
   {
    "type": "halberd",
    "route": [
     [
      22,
      2,
      0
     ]
    ],
    "looks": [
     1.5707963267948966,
     3.141592653589793
    ]
   },
   {
    "route": [
     [
      1,
      14,
      2
     ],
     [
      1,
      22,
      2
     ],
     [
      24,
      22,
      2
     ],
     [
      24,
      14,
      2
     ]
    ]
   },
   {
    "route": [
     [
      15,
      15,
      2
     ],
     [
      8,
      15,
      2
     ]
    ]
   }
  ],
  "nobles": [
   [
    17,
    19
   ]
  ],
  "civilians": [
   [
    7,
    20
   ],
   [
    18,
    16
   ]
  ],
  "gold": [
   [
    23,
    4,
    20
   ],
   [
    1,
    13,
    10
   ],
   [
    22,
    24,
    15
   ]
  ],
  "treasure": {
   "id": "keys",
   "name": "the Sheriff’s golden keys",
   "x": 21,
   "y": 3
  },
  "reward": 90,
  "tips": [
   {
    "id": "noRobin",
    "when": "start",
    "text": "No Robin today. Marian’s 🌹 Charm keeps a guard at his post but blind to you; Tuck’s 🍺 Ale puts any guard to sleep where he stands."
   },
   {
    "id": "check",
    "when": "nearGuard",
    "text": "The caped sergeant walks his round and checks on the gate guard. If that guard is gone from his post, the alarm goes up."
   }
  ],
  "map": [
   "TTTTTTTTTTTTTTTTTTTTTTTTTT",
   "T########################T",
   "T#dd#dd#dd#rrrrrrrr#ffff#T",
   "T#dd#dd#dd#rrrrrrrr#ffff#T",
   "T##f##f##f#rrrrrrrr#fccf#T",
   "T#ffffffffffffffffffffff#T",
   "T#ffffffffffffffffffffff#T",
   "T#fhhffffffffffffffffhff#T",
   "T#ffffffffffffffffffffff#T",
   "T###########ff###########T",
   "T..........,ff,..........T",
   "T.rrrr.....,,,,.....rrrr.T",
   "T.rrrr..............rrrr.T",
   "T.rrrr..b........b..rrrr.T",
   "T........................T",
   "T..rrrr..ffffffff..rrrr..T",
   "T..rrrr..f......f..rrrr..T",
   "T..rrrr..f..hh..f..rrrr..T",
   "T........f......f........T",
   "T.rrr....ffffffff....rrr.T",
   "T.rrr................rrr.T",
   "T.rrr..c..........c..rrr.T",
   "T........................T",
   "TT.b....rrr....rrr....b.TT",
   "TTT.....rrr....rrr.....TTT",
   "TTTT......,,,,,,......TTTT",
   "TTTTT.....,,,,,,.....TTTTT",
   "TTTTTTTTTTTTTTTTTTTTTTTTTT"
  ],
  "town": "Nottingham"
 },
 {
  "id": "m14",
  "rank": 13,
  "theme": "town",
  "title": "The Midnight Letter",
  "place": "York river stairs",
  "mapPos": [
   33,
   30
  ],
  "night": true,
  "kind": "story",
  "type": "Courier",
  "captive": [
   2,
   5
  ],
  "intro": "King Richard’s letter must reach the boatman at the end of the north pier tonight. Whoever carries it walks at full speed, but hold on to it: if he falls, it falls with him.\n\nThe Queen Mother has asked one thing. Not a drop of blood tonight: a single death and the boatman will not sail. Use nets, ale, the sling and bare fists.",
  "outro": "The boatman tucks the letter inside his coat and pushes off into the mist without a word.\n\nIn a week, the barons will know the King lives. Some will stay loyal to the Prince. Some will march with us. Robin calls them to York.",
  "heroes": {
   "robin": [
    4,
    25
   ],
   "john": [
    5,
    25
   ],
   "marian": [
    3,
    25
   ],
   "tuck": [
    6,
    25
   ],
   "scarlet": [
    4,
    26
   ]
  },
  "need": [
   "robin"
  ],
  "exit": {
   "x": 2,
   "y": 24,
   "w": 6,
   "h": 3
  },
  "chest": {
   "x": 6,
   "y": 24,
   "letter": true
  },
  "contacts": [
   {
    "id": "boatman",
    "name": "the boatman",
    "x": 26,
    "y": 7,
    "needs": "letter",
    "wait": "“No letter, no boat.”",
    "say": "“For the King.” He tucks it away and casts off."
   }
  ],
  "objectives": [
   "deliver",
   "exit"
  ],
  "torches": [
   [
    20,
    6
   ],
   [
    20,
    12
   ],
   [
    20,
    19
   ],
   [
    10,
    6
   ],
   [
    10,
    12
   ],
   [
    2,
    19
   ],
   [
    24,
    7
   ]
  ],
  "guards": [
   {
    "route": [
     [
      21,
      7,
      0
     ]
    ],
    "looks": [
     3.141592653589793,
     1.5707963267948966,
     -1.5707963267948966
    ]
   },
   {
    "route": [
     [
      20,
      2,
      2
     ],
     [
      20,
      17,
      2
     ]
    ]
   },
   {
    "type": "officer",
    "route": [
     [
      3,
      6,
      1
     ],
     [
      19,
      6,
      1
     ]
    ]
   },
   {
    "route": [
     [
      19,
      12,
      1
     ],
     [
      3,
      12,
      1
     ]
    ]
   },
   {
    "type": "archer",
    "route": [
     [
      19,
      4,
      0
     ]
    ],
    "looks": [
     1.5707963267948966,
     3.141592653589793
    ]
   },
   {
    "route": [
     [
      3,
      19,
      2
     ],
     [
      19,
      19,
      2
     ]
    ]
   },
   {
    "type": "halberd",
    "route": [
     [
      22,
      19,
      0
     ]
    ],
    "looks": [
     3.141592653589793,
     -1.5707963267948966
    ]
   },
   {
    "route": [
     [
      2,
      8,
      1
     ],
     [
      2,
      17,
      1
     ]
    ]
   },
   {
    "type": "knight",
    "route": [
     [
      12,
      17,
      0
     ]
    ],
    "looks": [
     -1.5707963267948966,
     0,
     3.141592653589793
    ]
   }
  ],
  "gold": [
   [
    17,
    5,
    20
   ],
   [
    9,
    18,
    15
   ],
   [
    23,
    19,
    20
   ]
  ],
  "reward": 100,
  "tips": [
   {
    "id": "letter",
    "when": "start",
    "text": "Pick up the letter by the cart. The carrier keeps full speed. Deliver it by walking up to the boatman and tapping him."
   }
  ],
  "map": [
   "TTTTTTTTTTTTTTTTTTTTwwwwwwww",
   "Trrrrr..rrrrrr..rrr.fwwwwwww",
   "Trrrrr..rrrrrr..rrr.fwwwwwww",
   "Trrrrr..rrrrrr..rrr.fwwwwwww",
   "T...................fwwwwwww",
   "T..cc......h......c.fwwwwwww",
   "T.ffffffffffffffffffffwwwwww",
   "T.f.................fddddddw",
   "T.f.rrrr..rrrr..rr..fwwwwwww",
   "T.f.rrrr..rrrr..rr..fwwwwwww",
   "T.f.rrrr..rrrr......fwwwwwww",
   "T.f.................fwwwwwww",
   "T.ffffffffffffffffffffwwwwww",
   "T.....c...h.....cc..fwwwwwww",
   "Trrrr..rrrrr..rrrr..fwwwwwww",
   "Trrrr..rrrrr..rrrr..fwwwwwww",
   "Trrrr..rrrrr..rrrr..fwwwwwww",
   "T...................fwwwwwww",
   "T..h...cc......c....fwwwwwww",
   "T.ffffffffffffffffffddddwwww",
   "T.f.................fwwwwwww",
   "T.f.rrrrr..rrrr..rr.fwwwwwww",
   "T.f.rrrrr..rrrr..rr.fwwwwwww",
   "T.f.................fwwwwwww",
   "Tb..................fwwwwwww",
   "T..,,,,.....b.......fwwwwwww",
   "TT.,,,,............TTwwwwwww",
   "TTTTTTTTTTTTTTTTTTTTwwwwwwww"
  ],
  "town": "York"
 },
 {
  "id": "m15",
  "rank": 14,
  "theme": "castle",
  "title": "The March on York",
  "place": "York, in the snow",
  "mapPos": [
   33,
   30
  ],
  "weather": "snow",
  "kind": "story",
  "type": "Siege",
  "captive": [
   17,
   6
  ],
  "intro": "Snow on the road, and two hundred of Aubrey’s men waiting in the woods south of York. They will not march on the walls until they see a sign.\n\nRing the minster bell, or raise the King’s standard on the citadel, and they will come. The river splits the city: both bridges are guarded. Soldiers never search a house unless they see you go in, so a house is a fine place to wait out a patrol. Beat the Prince’s general in the citadel.",
  "outro": "York falls by nightfall. The Prince’s captains surrender their swords to a ragged band in Lincoln green.\n\nOnly the Sheriff remains, in his keep at Nottingham, sitting on the taxes of three shires. And the King’s ransom is not yet paid.",
  "heroes": {
   "robin": [
    15,
    31
   ],
   "john": [
    16,
    31
   ],
   "marian": [
    15,
    32
   ],
   "tuck": [
    16,
    32
   ],
   "scarlet": [
    16,
    30
   ]
  },
  "need": [
   "robin"
  ],
  "exit": {
   "x": -9,
   "y": -9,
   "w": 1,
   "h": 1
  },
  "blazons": [],
  "allies": [
   [
    14,
    28
   ],
   [
    15,
    28
   ],
   [
    16,
    28
   ],
   [
    14,
    29
   ],
   [
    16,
    29
   ],
   [
    15,
    27
   ]
  ],
  "props": [
   {
    "id": "bell",
    "kind": "bell",
    "x": 6,
    "y": 4,
    "say": "The minster bell rings out over the snow! Aubrey’s men march on York."
   },
   {
    "id": "standard",
    "kind": "bell",
    "x": 21,
    "y": 4,
    "label": "⚑ Raise the King’s standard",
    "say": "The King’s standard flies over the citadel!"
   }
  ],
  "objectives": [
   {
    "k": "use",
    "id": "bell",
    "text": "Ring the minster bell"
   },
   {
    "k": "use",
    "id": "standard",
    "text": "Raise the standard on the citadel"
   },
   "boss"
  ],
  "guards": [
   {
    "route": [
     [
      14,
      25,
      0
     ]
    ],
    "type": "halberd",
    "looks": [
     1.5707963267948966,
     1.1707963267948966
    ]
   },
   {
    "route": [
     [
      17,
      25,
      0
     ]
    ],
    "type": "halberd",
    "looks": [
     1.5707963267948966,
     1.9707963267948965
    ]
   },
   {
    "route": [
     [
      3,
      19,
      2
     ],
     [
      28,
      19,
      2
     ]
    ],
    "type": "archer"
   },
   {
    "route": [
     [
      3,
      15,
      1
     ],
     [
      12,
      15,
      1
     ],
     [
      12,
      24,
      1
     ],
     [
      3,
      24,
      1
     ]
    ]
   },
   {
    "route": [
     [
      18,
      15,
      1
     ],
     [
      29,
      15,
      1
     ],
     [
      29,
      24,
      1
     ],
     [
      18,
      24,
      1
     ]
    ],
    "type": "archer"
   },
   {
    "route": [
     [
      8,
      15,
      0
     ]
    ],
    "type": "knight",
    "looks": [
     1.5707963267948966,
     1.0707963267948966
    ]
   },
   {
    "route": [
     [
      9,
      15,
      0
     ]
    ],
    "looks": [
     1.5707963267948966
    ]
   },
   {
    "route": [
     [
      7,
      12,
      0
     ]
    ],
    "type": "archer",
    "looks": [
     1.5707963267948966,
     0.0
    ]
   },
   {
    "route": [
     [
      10,
      12,
      0
     ]
    ],
    "type": "officer",
    "looks": [
     1.5707963267948966,
     3.141592653589793
    ]
   },
   {
    "route": [
     [
      22,
      15,
      0
     ]
    ],
    "type": "knight",
    "looks": [
     1.5707963267948966,
     2.0707963267948966
    ]
   },
   {
    "route": [
     [
      23,
      15,
      0
     ]
    ],
    "looks": [
     1.5707963267948966
    ]
   },
   {
    "route": [
     [
      21,
      12,
      0
     ]
    ],
    "type": "archer",
    "looks": [
     1.5707963267948966,
     3.141592653589793
    ]
   },
   {
    "route": [
     [
      24,
      12,
      0
     ]
    ],
    "type": "soldier",
    "looks": [
     1.5707963267948966,
     0.0
    ]
   },
   {
    "route": [
     [
      7,
      6,
      0
     ]
    ],
    "type": "halberd",
    "looks": [
     1.5707963267948966,
     0.0
    ]
   },
   {
    "route": [
     [
      10,
      4,
      0
     ]
    ],
    "type": "black",
    "looks": [
     3.141592653589793,
     1.5707963267948966
    ]
   },
   {
    "route": [
     [
      5,
      3,
      0
     ]
    ],
    "type": "black",
    "looks": [
     0.0,
     1.5707963267948966
    ]
   },
   {
    "route": [
     [
      23,
      8,
      0
     ]
    ],
    "type": "halberd",
    "looks": [
     1.5707963267948966,
     1.9707963267948965
    ]
   },
   {
    "route": [
     [
      20,
      6,
      1
     ],
     [
      27,
      6,
      1
     ]
    ],
    "type": "black"
   },
   {
    "route": [
     [
      20,
      3,
      0
     ]
    ],
    "type": "officer",
    "looks": [
     1.5707963267948966,
     0.0
    ]
   },
   {
    "route": [
     [
      26,
      7,
      0
     ]
    ],
    "type": "boss",
    "looks": [
     1.5707963267948966,
     3.141592653589793
    ],
    "boss": true,
    "name": "Lord Fitzwalter"
   }
  ],
  "gold": [
   [
    2,
    2,
    30
   ],
   [
    27,
    7,
    30
   ],
   [
    2,
    20,
    15
   ],
   [
    29,
    23,
    15
   ],
   [
    15,
    6,
    25
   ]
  ],
  "treasure": {
   "id": "crown",
   "name": "the Crown of Ravenscar",
   "x": 27,
   "y": 7
  },
  "reward": 110,
  "tips": [
   {
    "id": "houses",
    "when": "start",
    "text": "Patrols with crossbows notice missing friends. Duck into a house when one passes: they won’t search it unless they saw you go in."
   }
  ],
  "map": [
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
   "T##############################T",
   "T#f##########ffffff##########f#T",
   "T#f#dddddddd#frrrff#ffffrrrr#f#T",
   "T#f#dddddddd#frrrff#ffffrrrr#f#T",
   "T#f#dddddddd#frrrff#ffffrrrr#f#T",
   "T#f#dddddddd#ffffff#ffffffff#f#T",
   "T#f#dddddddd#ffffff#ffffffff#f#T",
   "T#f####ff####frrrff#ffffffff#f#T",
   "T#ffffffffffffrrrff####f#####f#T",
   "T#frrrffffffffrrrfffffffffrrrf#T",
   "T#frrrcfffffhffffcffffffffrrrf#T",
   "T#ffffffffffffffffffffffffffff#T",
   "T#wwwwwwddwwwwwwwwwwwwddwwwwww#T",
   "T#wwwwwwddwwwwwwwwwwwwddwwwwww#T",
   "T#ffffffffffffffffffffffffffff#T",
   "T#frrrffffffffrrrffffffffrrrff#T",
   "T#frrrffrrrfffrrrffrrrfffrrrff#T",
   "T#frrrffrrrfffrrrffrrrfffrrrff#T",
   "T#ffffffrrrffffffffrrrffffffhf#T",
   "T#fffffffffcfffffffffffcffffff#T",
   "T#frrrffffffrrrffffffffffrrrff#T",
   "T#frrrffffffrrrffffrrrfffrrrff#T",
   "T#frrrfffffffffffffrrrfffrrrff#T",
   "T#hffffffffffffffcffffffffffff#T",
   "T#ffffffffffffffffffffffffffff#T",
   "T##############ff##############T",
   "T..bT..........,,.bbT...T......T",
   "T............T.,,..bbT..T..T...T",
   "T.............T,,.........Tb...T",
   "T....bbT...T..T,,.b.......T....T",
   "T..............,,T...T..T...T..T",
   "T.T...T.....T..,,T..b...T...T..T",
   "TTTTTTTTTTTTTTT,,TTTTTTTTTTTTTTT"
  ],
  "town": "York",
  "torches": [],
  "clovers": [
   [
    11,
    3
   ]
  ]
 },
 {
  "id": "m16",
  "rank": 15,
  "theme": "castle",
  "title": "The Last Arrow",
  "place": "The Sheriff’s keep",
  "mapPos": [
   55,
   56
  ],
  "night": true,
  "kind": "story",
  "type": "Final challenge",
  "climbs": [
   [
    6,
    20,
    6,
    18
   ]
  ],
  "needRansom": true,
  "intro": "The ransom is paid, and King Richard is on the road home. One debt is left to settle.\n\nThe band goes in from two sides: Robin, Marian and Will by the moat, John and Tuck from the hay cart already inside the lower yard. Capture the Sheriff alive and tie him up, take the tax chest from the treasury, and get everyone out over the moat.",
  "outro": "The Sheriff, trussed like a Michaelmas goose, is left on the abbey steps with a note pinned to his cloak, in a hand that every child in the shire now knows.\n\nThe taxes go home. The King comes home. And somewhere in Sherwood an arrow is fitted to a string, just in case.",
  "heroes": {
   "robin": [
    14,
    25
   ],
   "marian": [
    13,
    25
   ],
   "scarlet": [
    12,
    25
   ],
   "john": [
    2,
    15
   ],
   "tuck": [
    3,
    15
   ]
  },
  "need": [
   "robin",
   "john"
  ],
  "exit": {
   "x": 10,
   "y": 23,
   "w": 8,
   "h": 3
  },
  "chest": {
   "x": 2,
   "y": 10
  },
  "sheriff": {
   "x": 14,
   "y": 3
  },
  "objectives": [
   "sheriff",
   "steal",
   "exit"
  ],
  "reinforce": [
   [
    14,
    18,
    "knight"
   ],
   [
    15,
    18,
    "soldier"
   ],
   [
    13,
    17,
    "archer"
   ]
  ],
  "torches": [
   [
    13,
    7
   ],
   [
    16,
    7
   ],
   [
    10,
    15
   ],
   [
    19,
    15
   ],
   [
    11,
    18
   ],
   [
    16,
    18
   ],
   [
    6,
    2
   ],
   [
    23,
    2
   ],
   [
    8,
    9
   ]
  ],
  "guards": [
   {
    "type": "knight",
    "route": [
     [
      5,
      5,
      2
     ],
     [
      24,
      5,
      2
     ]
    ]
   },
   {
    "type": "black",
    "route": [
     [
      12,
      7,
      0
     ]
    ],
    "looks": [
     1.5707963267948966,
     0.9707963267948966,
     1.9707963267948965
    ]
   },
   {
    "type": "black",
    "route": [
     [
      17,
      7,
      0
     ]
    ],
    "looks": [
     1.5707963267948966,
     2.1707963267948966,
     1.1707963267948966
    ]
   },
   {
    "route": [
     [
      9,
      14,
      1
     ],
     [
      20,
      14,
      1
     ],
     [
      20,
      17,
      1
     ],
     [
      9,
      17,
      1
     ]
    ]
   },
   {
    "type": "halberd",
    "route": [
     [
      12,
      18,
      0
     ]
    ],
    "looks": [
     1.5707963267948966,
     1.0707963267948966,
     1.5707963267948966
    ]
   },
   {
    "route": [
     [
      15,
      18,
      0
     ]
    ],
    "looks": [
     1.5707963267948966,
     2.0707963267948966,
     1.5707963267948966
    ]
   },
   {
    "type": "officer",
    "route": [
     [
      4,
      10,
      0
     ]
    ],
    "looks": [
     0,
     -0.6,
     0.6
    ]
   },
   {
    "route": [
     [
      4,
      17,
      3
     ],
     [
      10,
      17,
      3
     ]
    ]
   },
   {
    "type": "archer",
    "route": [
     [
      24,
      7,
      2
     ],
     [
      28,
      7,
      2
     ],
     [
      28,
      16,
      2
     ]
    ]
   },
   {
    "type": "black",
    "route": [
     [
      22,
      3,
      0
     ]
    ],
    "looks": [
     3.141592653589793,
     1.5707963267948966
    ]
   }
  ],
  "gold": [
   [
    27,
    9,
    20
   ],
   [
    1,
    12,
    20
   ],
   [
    5,
    2,
    25
   ],
   [
    24,
    12,
    15
   ]
  ],
  "reward": 150,
  "tips": [
   {
    "id": "split",
    "when": "start",
    "text": "Two groups: John and Tuck start inside the lower yard. Tap a portrait twice to select one group, or use 👥 All."
   },
   {
    "id": "sheriff",
    "when": "nearGuard",
    "text": "Black-cloaked guards hold their posts and won’t chase you far. The Sheriff is tough: knock him out or beat him, then tie him up."
   }
  ],
  "map": [
   "##############################",
   "#rrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
   "#rr#dddddddddddddddddddddd#rr#",
   "#rr#dddddddddddddddddddddd#rr#",
   "#rr#dd##dddddddddddddd##dd#rr#",
   "#rr#dddddddddddddddddddddd#rr#",
   "#rr##########dddd#####dd###rr#",
   "#ffffffffffffffffffffffffffff#",
   "#########ffffffffffff#########",
   "#fffffff#ffffffffffff#hhfffff#",
   "#ffffffffffffffffffffffffffff#",
   "#fffffff#ffffffffffff#fffffff#",
   "#fffffff#ffffwwwwffff#ccfffff#",
   "#########ffffwwwwffff#########",
   "#ffffffffffffffffffffffffffff#",
   "#fhhff##ffffffffffffff##ffhff#",
   "#ffffffffffffffffffffffffffff#",
   "#ccfffffffffffffffffffffffccf#",
   "#ffffffffffffffffffffffffffff#",
   "##f#########ffff##############",
   "TT..b.......,,,,.......b...TTT",
   "TT,wwwwwwwww,,,,wwwwwwwwwwwwTT",
   "TT.....b....,,,,....b......TTT",
   "TTT.........,,,,.........TTTTT",
   "TTTTb.......,,,,.......bTTTTTT",
   "TTTTTT......,,,,......TTTTTTTT",
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT"
  ],
  "town": "Nottingham"
 }
];
  RH.MISSIONS.forEach((m, i) => { m.idx = i; });
})(window.RH);
